version: 2
updates:
  - package-ecosystem: "gomod"
    assignees:
      - "pierskarsenbarg"
    directory: "/provider"
    schedule:
      interval: "weekly"
      time: "08:00"
      day: "sunday"
    commit-message:
      prefix: "provider"
      include: "scope"
    ignore:
      - dependency-name: "github.com/pulumi/pulumi/sdk/*"
  - package-ecosystem: "gomod"
    assignees:
      - "pierskarsenbarg"
    directory: "/sdk"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
    commit-message:
      prefix: "sdk"
      include: "scope"
  - package-ecosystem: "github-actions"
    assignees:
      - "pierskarsenbarg"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    commit-message:
      prefix: "gha"
      include: "scope"
