// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix
{
    public static class GetNetworkSecurityPoliciesV2
    {
        /// <summary>
        /// Gets a list of Network Security Policies.
        /// </summary>
        public static Task<GetNetworkSecurityPoliciesV2Result> InvokeAsync(GetNetworkSecurityPoliciesV2Args? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNetworkSecurityPoliciesV2Result>("nutanix:index/getNetworkSecurityPoliciesV2:getNetworkSecurityPoliciesV2", args ?? new GetNetworkSecurityPoliciesV2Args(), options.WithDefaults());

        /// <summary>
        /// Gets a list of Network Security Policies.
        /// </summary>
        public static Output<GetNetworkSecurityPoliciesV2Result> Invoke(GetNetworkSecurityPoliciesV2InvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworkSecurityPoliciesV2Result>("nutanix:index/getNetworkSecurityPoliciesV2:getNetworkSecurityPoliciesV2", args ?? new GetNetworkSecurityPoliciesV2InvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Gets a list of Network Security Policies.
        /// </summary>
        public static Output<GetNetworkSecurityPoliciesV2Result> Invoke(GetNetworkSecurityPoliciesV2InvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworkSecurityPoliciesV2Result>("nutanix:index/getNetworkSecurityPoliciesV2:getNetworkSecurityPoliciesV2", args ?? new GetNetworkSecurityPoliciesV2InvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNetworkSecurityPoliciesV2Args : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A URL query parameter that allows clients to filter a collection of resources. The filter can be applied to the following fields:
        /// - createdBy
        /// - description
        /// - extId
        /// - isHitlogEnabled
        /// - isIpv6TrafficAllowed
        /// - isSystemDefined
        /// - name
        /// - securedGroups
        /// - state
        /// - type
        /// - vpcReference
        /// </summary>
        [Input("filter")]
        public string? Filter { get; set; }

        /// <summary>
        /// A URL query parameter that specifies the total number of records returned in the result set. Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set.
        /// </summary>
        [Input("limit")]
        public int? Limit { get; set; }

        /// <summary>
        /// A URL query parameter that allows clients to specify the sort criteria for the returned list of objects. Resources can be sorted in ascending order using asc or descending order using desc. If asc or desc are not specified, the resources will be sorted in ascending order by default. The orderby can be applied to the following fields:
        /// - creationTime
        /// - description
        /// - extId
        /// - isSystemDefined
        /// - lastUpdateTime
        /// - name
        /// - state
        /// - type
        /// </summary>
        [Input("orderBy")]
        public string? OrderBy { get; set; }

        /// <summary>
        /// A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results.
        /// </summary>
        [Input("page")]
        public int? Page { get; set; }

        /// <summary>
        /// A URL query parameter that allows clients to request a specific set of properties for each entity or complex type. The select can be applied to the following fields:
        /// 
        /// - createdBy
        /// - creationTime
        /// - description
        /// - extId
        /// - isHitlogEnabled
        /// - isIpv6TrafficAllowed
        /// - isSystemDefined
        /// - lastUpdateTime
        /// - links
        /// - name
        /// - rules
        /// - scope
        /// - securedGroups
        /// - state
        /// - tenantId
        /// - type
        /// - vpcReference
        /// </summary>
        [Input("select")]
        public string? Select { get; set; }

        public GetNetworkSecurityPoliciesV2Args()
        {
        }
        public static new GetNetworkSecurityPoliciesV2Args Empty => new GetNetworkSecurityPoliciesV2Args();
    }

    public sealed class GetNetworkSecurityPoliciesV2InvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A URL query parameter that allows clients to filter a collection of resources. The filter can be applied to the following fields:
        /// - createdBy
        /// - description
        /// - extId
        /// - isHitlogEnabled
        /// - isIpv6TrafficAllowed
        /// - isSystemDefined
        /// - name
        /// - securedGroups
        /// - state
        /// - type
        /// - vpcReference
        /// </summary>
        [Input("filter")]
        public Input<string>? Filter { get; set; }

        /// <summary>
        /// A URL query parameter that specifies the total number of records returned in the result set. Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set.
        /// </summary>
        [Input("limit")]
        public Input<int>? Limit { get; set; }

        /// <summary>
        /// A URL query parameter that allows clients to specify the sort criteria for the returned list of objects. Resources can be sorted in ascending order using asc or descending order using desc. If asc or desc are not specified, the resources will be sorted in ascending order by default. The orderby can be applied to the following fields:
        /// - creationTime
        /// - description
        /// - extId
        /// - isSystemDefined
        /// - lastUpdateTime
        /// - name
        /// - state
        /// - type
        /// </summary>
        [Input("orderBy")]
        public Input<string>? OrderBy { get; set; }

        /// <summary>
        /// A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results.
        /// </summary>
        [Input("page")]
        public Input<int>? Page { get; set; }

        /// <summary>
        /// A URL query parameter that allows clients to request a specific set of properties for each entity or complex type. The select can be applied to the following fields:
        /// 
        /// - createdBy
        /// - creationTime
        /// - description
        /// - extId
        /// - isHitlogEnabled
        /// - isIpv6TrafficAllowed
        /// - isSystemDefined
        /// - lastUpdateTime
        /// - links
        /// - name
        /// - rules
        /// - scope
        /// - securedGroups
        /// - state
        /// - tenantId
        /// - type
        /// - vpcReference
        /// </summary>
        [Input("select")]
        public Input<string>? Select { get; set; }

        public GetNetworkSecurityPoliciesV2InvokeArgs()
        {
        }
        public static new GetNetworkSecurityPoliciesV2InvokeArgs Empty => new GetNetworkSecurityPoliciesV2InvokeArgs();
    }


    [OutputType]
    public sealed class GetNetworkSecurityPoliciesV2Result
    {
        public readonly string? Filter;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly int? Limit;
        public readonly ImmutableArray<Outputs.GetNetworkSecurityPoliciesV2NetworkPolicyResult> NetworkPolicies;
        public readonly string? OrderBy;
        public readonly int? Page;
        public readonly string? Select;

        [OutputConstructor]
        private GetNetworkSecurityPoliciesV2Result(
            string? filter,

            string id,

            int? limit,

            ImmutableArray<Outputs.GetNetworkSecurityPoliciesV2NetworkPolicyResult> networkPolicies,

            string? orderBy,

            int? page,

            string? select)
        {
            Filter = filter;
            Id = id;
            Limit = limit;
            NetworkPolicies = networkPolicies;
            OrderBy = orderBy;
            Page = page;
            Select = select;
        }
    }
}
