// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetClusterProfileV2NtpServerIpListFqdnResult
    {
        /// <summary>
        /// - (Required) Ip address.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private GetClusterProfileV2NtpServerIpListFqdnResult(string value)
        {
            Value = value;
        }
    }
}
