// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetFloatingIpsV2FloatingIpAssociationResult
    {
        /// <summary>
        /// Association of Floating IP with private IP
        /// </summary>
        public readonly ImmutableArray<Outputs.GetFloatingIpsV2FloatingIpAssociationPrivateIpAssociationResult> PrivateIpAssociations;
        /// <summary>
        /// Association of Floating IP with nic
        /// </summary>
        public readonly ImmutableArray<Outputs.GetFloatingIpsV2FloatingIpAssociationVmNicAssociationResult> VmNicAssociations;

        [OutputConstructor]
        private GetFloatingIpsV2FloatingIpAssociationResult(
            ImmutableArray<Outputs.GetFloatingIpsV2FloatingIpAssociationPrivateIpAssociationResult> privateIpAssociations,

            ImmutableArray<Outputs.GetFloatingIpsV2FloatingIpAssociationVmNicAssociationResult> vmNicAssociations)
        {
            PrivateIpAssociations = privateIpAssociations;
            VmNicAssociations = vmNicAssociations;
        }
    }
}
