// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetFloatingIpV2ExternalSubnetIpConfigResult
    {
        /// <summary>
        /// Reference to IP Configuration
        /// </summary>
        public readonly ImmutableArray<Outputs.GetFloatingIpV2ExternalSubnetIpConfigIpv4Result> Ipv4s;
        /// <summary>
        /// Reference to IP Configuration
        /// </summary>
        public readonly ImmutableArray<Outputs.GetFloatingIpV2ExternalSubnetIpConfigIpv6Result> Ipv6s;

        [OutputConstructor]
        private GetFloatingIpV2ExternalSubnetIpConfigResult(
            ImmutableArray<Outputs.GetFloatingIpV2ExternalSubnetIpConfigIpv4Result> ipv4s,

            ImmutableArray<Outputs.GetFloatingIpV2ExternalSubnetIpConfigIpv6Result> ipv6s)
        {
            Ipv4s = ipv4s;
            Ipv6s = ipv6s;
        }
    }
}
