// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetKeyManagementServerV2AccessInformationKmipKeyVaultEndpointUrlIpAddressResult
    {
        /// <summary>
        /// FQDN of the External Key Manager server.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetKeyManagementServerV2AccessInformationKmipKeyVaultEndpointUrlIpAddressFqdnResult> Fqdns;
        /// <summary>
        /// IPv4 address of the External Key Manager server.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetKeyManagementServerV2AccessInformationKmipKeyVaultEndpointUrlIpAddressIpv4Result> Ipv4s;
        /// <summary>
        /// IPv6 address of the External Key Manager server.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetKeyManagementServerV2AccessInformationKmipKeyVaultEndpointUrlIpAddressIpv6Result> Ipv6s;

        [OutputConstructor]
        private GetKeyManagementServerV2AccessInformationKmipKeyVaultEndpointUrlIpAddressResult(
            ImmutableArray<Outputs.GetKeyManagementServerV2AccessInformationKmipKeyVaultEndpointUrlIpAddressFqdnResult> fqdns,

            ImmutableArray<Outputs.GetKeyManagementServerV2AccessInformationKmipKeyVaultEndpointUrlIpAddressIpv4Result> ipv4s,

            ImmutableArray<Outputs.GetKeyManagementServerV2AccessInformationKmipKeyVaultEndpointUrlIpAddressIpv6Result> ipv6s)
        {
            Fqdns = fqdns;
            Ipv4s = ipv4s;
            Ipv6s = ipv6s;
        }
    }
}
