// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetNdbTmsCapabilityLastContinuousSnapshotLcmConfigExpiryDetailResult
    {
        public readonly bool DeleteDatabase;
        public readonly bool DeleteTimeMachine;
        public readonly bool DeleteVm;
        public readonly string EffectiveTimestamp;
        public readonly int ExpireInDays;
        public readonly string ExpiryDateTimezone;
        public readonly string ExpiryTimestamp;
        public readonly int RemindBeforeInDays;
        public readonly bool UserCreated;

        [OutputConstructor]
        private GetNdbTmsCapabilityLastContinuousSnapshotLcmConfigExpiryDetailResult(
            bool deleteDatabase,

            bool deleteTimeMachine,

            bool deleteVm,

            string effectiveTimestamp,

            int expireInDays,

            string expiryDateTimezone,

            string expiryTimestamp,

            int remindBeforeInDays,

            bool userCreated)
        {
            DeleteDatabase = deleteDatabase;
            DeleteTimeMachine = deleteTimeMachine;
            DeleteVm = deleteVm;
            EffectiveTimestamp = effectiveTimestamp;
            ExpireInDays = expireInDays;
            ExpiryDateTimezone = expiryDateTimezone;
            ExpiryTimestamp = expiryTimestamp;
            RemindBeforeInDays = remindBeforeInDays;
            UserCreated = userCreated;
        }
    }
}
