// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetOvaV2VmConfigOwnershipInfoResult
    {
        /// <summary>
        /// Reference to the owner.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetOvaV2VmConfigOwnershipInfoOwnerResult> Owners;

        [OutputConstructor]
        private GetOvaV2VmConfigOwnershipInfoResult(ImmutableArray<Outputs.GetOvaV2VmConfigOwnershipInfoOwnerResult> owners)
        {
            Owners = owners;
        }
    }
}
