// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetOvaV2VmConfigGuestCustomizationConfigSysprepSysprepScriptResult
    {
        /// <summary>
        /// The list of the individual KeyValuePair elements.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetOvaV2VmConfigGuestCustomizationConfigSysprepSysprepScriptCustomKeyValueResult> CustomKeyValues;
        /// <summary>
        /// xml object
        /// </summary>
        public readonly ImmutableArray<Outputs.GetOvaV2VmConfigGuestCustomizationConfigSysprepSysprepScriptUnattendXmlResult> UnattendXmls;

        [OutputConstructor]
        private GetOvaV2VmConfigGuestCustomizationConfigSysprepSysprepScriptResult(
            ImmutableArray<Outputs.GetOvaV2VmConfigGuestCustomizationConfigSysprepSysprepScriptCustomKeyValueResult> customKeyValues,

            ImmutableArray<Outputs.GetOvaV2VmConfigGuestCustomizationConfigSysprepSysprepScriptUnattendXmlResult> unattendXmls)
        {
            CustomKeyValues = customKeyValues;
            UnattendXmls = unattendXmls;
        }
    }
}
