// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetOvaV2VmConfigCdRomBackingInfoDataSourceResult
    {
        /// <summary>
        /// Reference to image or vm disk
        /// </summary>
        public readonly ImmutableArray<Outputs.GetOvaV2VmConfigCdRomBackingInfoDataSourceReferenceResult> References;

        [OutputConstructor]
        private GetOvaV2VmConfigCdRomBackingInfoDataSourceResult(ImmutableArray<Outputs.GetOvaV2VmConfigCdRomBackingInfoDataSourceReferenceResult> references)
        {
            References = references;
        }
    }
}
