// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetPcsV2PcNetworkExternalNetworkSubnetMaskResult
    {
        public readonly ImmutableArray<Outputs.GetPcsV2PcNetworkExternalNetworkSubnetMaskFqdnResult> Fqdns;
        public readonly ImmutableArray<Outputs.GetPcsV2PcNetworkExternalNetworkSubnetMaskIpv4Result> Ipv4s;
        public readonly ImmutableArray<Outputs.GetPcsV2PcNetworkExternalNetworkSubnetMaskIpv6Result> Ipv6s;

        [OutputConstructor]
        private GetPcsV2PcNetworkExternalNetworkSubnetMaskResult(
            ImmutableArray<Outputs.GetPcsV2PcNetworkExternalNetworkSubnetMaskFqdnResult> fqdns,

            ImmutableArray<Outputs.GetPcsV2PcNetworkExternalNetworkSubnetMaskIpv4Result> ipv4s,

            ImmutableArray<Outputs.GetPcsV2PcNetworkExternalNetworkSubnetMaskIpv6Result> ipv6s)
        {
            Fqdns = fqdns;
            Ipv4s = ipv4s;
            Ipv6s = ipv6s;
        }
    }
}
