// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetPbrsV2RoutingPolicyPolicyPolicyMatchResult
    {
        /// <summary>
        /// Address Type like "EXTERNAL" or "ANY".
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPbrsV2RoutingPolicyPolicyPolicyMatchDestinationResult> Destinations;
        /// <summary>
        /// Protocol Params Object.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPbrsV2RoutingPolicyPolicyPolicyMatchProtocolParameterResult> ProtocolParameters;
        /// <summary>
        /// Routing Policy IP protocol type.
        /// </summary>
        public readonly string ProtocolType;
        /// <summary>
        /// Address Type like "EXTERNAL" or "ANY".
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPbrsV2RoutingPolicyPolicyPolicyMatchSourceResult> Sources;

        [OutputConstructor]
        private GetPbrsV2RoutingPolicyPolicyPolicyMatchResult(
            ImmutableArray<Outputs.GetPbrsV2RoutingPolicyPolicyPolicyMatchDestinationResult> destinations,

            ImmutableArray<Outputs.GetPbrsV2RoutingPolicyPolicyPolicyMatchProtocolParameterResult> protocolParameters,

            string protocolType,

            ImmutableArray<Outputs.GetPbrsV2RoutingPolicyPolicyPolicyMatchSourceResult> sources)
        {
            Destinations = destinations;
            ProtocolParameters = protocolParameters;
            ProtocolType = protocolType;
            Sources = sources;
        }
    }
}
