// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetRecoveryPlansEntityStageListStageWorkRecoverEntityEntityInfoListResult
    {
        public readonly string AnyEntityReferenceKind;
        public readonly string AnyEntityReferenceName;
        public readonly string AnyEntityReferenceUuid;
        public readonly ImmutableArray<Outputs.GetRecoveryPlansEntityStageListStageWorkRecoverEntityEntityInfoListCategoryResult> Categories;
        public readonly ImmutableArray<Outputs.GetRecoveryPlansEntityStageListStageWorkRecoverEntityEntityInfoListScriptListResult> ScriptLists;

        [OutputConstructor]
        private GetRecoveryPlansEntityStageListStageWorkRecoverEntityEntityInfoListResult(
            string anyEntityReferenceKind,

            string anyEntityReferenceName,

            string anyEntityReferenceUuid,

            ImmutableArray<Outputs.GetRecoveryPlansEntityStageListStageWorkRecoverEntityEntityInfoListCategoryResult> categories,

            ImmutableArray<Outputs.GetRecoveryPlansEntityStageListStageWorkRecoverEntityEntityInfoListScriptListResult> scriptLists)
        {
            AnyEntityReferenceKind = anyEntityReferenceKind;
            AnyEntityReferenceName = anyEntityReferenceName;
            AnyEntityReferenceUuid = anyEntityReferenceUuid;
            Categories = categories;
            ScriptLists = scriptLists;
        }
    }
}
