// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetSubnetsV2SubnetIpConfigIpv4Result
    {
        public readonly ImmutableArray<Outputs.GetSubnetsV2SubnetIpConfigIpv4DefaultGatewayIpResult> DefaultGatewayIps;
        public readonly ImmutableArray<Outputs.GetSubnetsV2SubnetIpConfigIpv4DhcpServerAddressResult> DhcpServerAddresses;
        public readonly ImmutableArray<Outputs.GetSubnetsV2SubnetIpConfigIpv4IpSubnetResult> IpSubnets;
        public readonly ImmutableArray<Outputs.GetSubnetsV2SubnetIpConfigIpv4PoolListResult> PoolLists;

        [OutputConstructor]
        private GetSubnetsV2SubnetIpConfigIpv4Result(
            ImmutableArray<Outputs.GetSubnetsV2SubnetIpConfigIpv4DefaultGatewayIpResult> defaultGatewayIps,

            ImmutableArray<Outputs.GetSubnetsV2SubnetIpConfigIpv4DhcpServerAddressResult> dhcpServerAddresses,

            ImmutableArray<Outputs.GetSubnetsV2SubnetIpConfigIpv4IpSubnetResult> ipSubnets,

            ImmutableArray<Outputs.GetSubnetsV2SubnetIpConfigIpv4PoolListResult> poolLists)
        {
            DefaultGatewayIps = defaultGatewayIps;
            DhcpServerAddresses = dhcpServerAddresses;
            IpSubnets = ipSubnets;
            PoolLists = poolLists;
        }
    }
}
