// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetStaticRoutesSpecResourceDefaultRouteNexthopResult
    {
        /// <summary>
        /// The reference to a direct_connect_virtual_interface
        /// </summary>
        public readonly ImmutableDictionary<string, string> DirectConnectVirtualInterfaceReference;
        /// <summary>
        /// The reference to a subnet
        /// </summary>
        public readonly ImmutableDictionary<string, string> ExternalSubnetReference;
        /// <summary>
        /// The reference to a subnet
        /// </summary>
        public readonly ImmutableDictionary<string, string> LocalSubnetReference;
        /// <summary>
        /// The reference to a vpn_connection
        /// </summary>
        public readonly ImmutableDictionary<string, string> VpnConnectionReference;

        [OutputConstructor]
        private GetStaticRoutesSpecResourceDefaultRouteNexthopResult(
            ImmutableDictionary<string, string> directConnectVirtualInterfaceReference,

            ImmutableDictionary<string, string> externalSubnetReference,

            ImmutableDictionary<string, string> localSubnetReference,

            ImmutableDictionary<string, string> vpnConnectionReference)
        {
            DirectConnectVirtualInterfaceReference = directConnectVirtualInterfaceReference;
            ExternalSubnetReference = externalSubnetReference;
            LocalSubnetReference = localSubnetReference;
            VpnConnectionReference = vpnConnectionReference;
        }
    }
}
