// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetStaticRoutesSpecResult
    {
        /// <summary>
        /// - the name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// VPC route table resources status
        /// </summary>
        public readonly ImmutableArray<Outputs.GetStaticRoutesSpecResourceResult> Resources;

        [OutputConstructor]
        private GetStaticRoutesSpecResult(
            string name,

            ImmutableArray<Outputs.GetStaticRoutesSpecResourceResult> resources)
        {
            Name = name;
            Resources = resources;
        }
    }
}
