// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetTemplatesV2TemplateTemplateVersionSpecVmSpecDiskResult
    {
        public readonly ImmutableArray<Outputs.GetTemplatesV2TemplateTemplateVersionSpecVmSpecDiskBackingInfoResult> BackingInfos;
        public readonly ImmutableArray<Outputs.GetTemplatesV2TemplateTemplateVersionSpecVmSpecDiskDiskAddressResult> DiskAddresses;
        public readonly string ExtId;
        public readonly ImmutableArray<Outputs.GetTemplatesV2TemplateTemplateVersionSpecVmSpecDiskLinkResult> Links;
        public readonly string TenantId;

        [OutputConstructor]
        private GetTemplatesV2TemplateTemplateVersionSpecVmSpecDiskResult(
            ImmutableArray<Outputs.GetTemplatesV2TemplateTemplateVersionSpecVmSpecDiskBackingInfoResult> backingInfos,

            ImmutableArray<Outputs.GetTemplatesV2TemplateTemplateVersionSpecVmSpecDiskDiskAddressResult> diskAddresses,

            string extId,

            ImmutableArray<Outputs.GetTemplatesV2TemplateTemplateVersionSpecVmSpecDiskLinkResult> links,

            string tenantId)
        {
            BackingInfos = backingInfos;
            DiskAddresses = diskAddresses;
            ExtId = extId;
            Links = links;
            TenantId = tenantId;
        }
    }
}
