// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetTemplateV2UpdatedByAdditionalAttributeResult
    {
        /// <summary>
        /// Name of the GPU resource.
        /// </summary>
        public readonly string Name;
        public readonly ImmutableArray<Outputs.GetTemplateV2UpdatedByAdditionalAttributeValueResult> Values;

        [OutputConstructor]
        private GetTemplateV2UpdatedByAdditionalAttributeResult(
            string name,

            ImmutableArray<Outputs.GetTemplateV2UpdatedByAdditionalAttributeValueResult> values)
        {
            Name = name;
            Values = values;
        }
    }
}
