// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetTemplateV2TemplateVersionSpecVmSpecNicResult
    {
        /// <summary>
        /// Defines a NIC emulated by the hypervisor
        /// </summary>
        public readonly ImmutableArray<Outputs.GetTemplateV2TemplateVersionSpecVmSpecNicBackingInfoResult> BackingInfos;
        /// <summary>
        /// The identifier of a Template.
        /// </summary>
        public readonly string ExtId;
        public readonly ImmutableArray<Outputs.GetTemplateV2TemplateVersionSpecVmSpecNicLinkResult> Links;
        /// <summary>
        /// Network information for a NIC.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetTemplateV2TemplateVersionSpecVmSpecNicNetworkInfoResult> NetworkInfos;
        public readonly string TenantId;

        [OutputConstructor]
        private GetTemplateV2TemplateVersionSpecVmSpecNicResult(
            ImmutableArray<Outputs.GetTemplateV2TemplateVersionSpecVmSpecNicBackingInfoResult> backingInfos,

            string extId,

            ImmutableArray<Outputs.GetTemplateV2TemplateVersionSpecVmSpecNicLinkResult> links,

            ImmutableArray<Outputs.GetTemplateV2TemplateVersionSpecVmSpecNicNetworkInfoResult> networkInfos,

            string tenantId)
        {
            BackingInfos = backingInfos;
            ExtId = extId;
            Links = links;
            NetworkInfos = networkInfos;
            TenantId = tenantId;
        }
    }
}
