// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetUserKeysV2KeyKeyDetailResult
    {
        public readonly ImmutableArray<Outputs.GetUserKeysV2KeyKeyDetailApiKeyDetailResult> ApiKeyDetails;
        public readonly ImmutableArray<Outputs.GetUserKeysV2KeyKeyDetailObjectKeyDetailResult> ObjectKeyDetails;

        [OutputConstructor]
        private GetUserKeysV2KeyKeyDetailResult(
            ImmutableArray<Outputs.GetUserKeysV2KeyKeyDetailApiKeyDetailResult> apiKeyDetails,

            ImmutableArray<Outputs.GetUserKeysV2KeyKeyDetailObjectKeyDetailResult> objectKeyDetails)
        {
            ApiKeyDetails = apiKeyDetails;
            ObjectKeyDetails = objectKeyDetails;
        }
    }
}
