// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetVpcV2CommonDhcpOptionDomainNameServerResult
    {
        /// <summary>
        /// Reference to address configuration
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVpcV2CommonDhcpOptionDomainNameServerIpv4Result> Ipv4s;
        /// <summary>
        /// Reference to address configuration
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVpcV2CommonDhcpOptionDomainNameServerIpv6Result> Ipv6s;

        [OutputConstructor]
        private GetVpcV2CommonDhcpOptionDomainNameServerResult(
            ImmutableArray<Outputs.GetVpcV2CommonDhcpOptionDomainNameServerIpv4Result> ipv4s,

            ImmutableArray<Outputs.GetVpcV2CommonDhcpOptionDomainNameServerIpv6Result> ipv6s)
        {
            Ipv4s = ipv4s;
            Ipv6s = ipv6s;
        }
    }
}
