// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetVpcV2ExternalSubnetActiveGatewayNodeResult
    {
        public readonly string NodeId;
        public readonly ImmutableArray<Outputs.GetVpcV2ExternalSubnetActiveGatewayNodeNodeIpAddressResult> NodeIpAddresses;

        [OutputConstructor]
        private GetVpcV2ExternalSubnetActiveGatewayNodeResult(
            string nodeId,

            ImmutableArray<Outputs.GetVpcV2ExternalSubnetActiveGatewayNodeNodeIpAddressResult> nodeIpAddresses)
        {
            NodeId = nodeId;
            NodeIpAddresses = nodeIpAddresses;
        }
    }
}
