// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetVolumeGroupsV2VolumeStorageFeatureResult
    {
        /// <summary>
        /// - this field will avoid down migration of data from the hot tier unless the overrides field is specified for the virtual disks.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVolumeGroupsV2VolumeStorageFeatureFlashModeResult> FlashModes;

        [OutputConstructor]
        private GetVolumeGroupsV2VolumeStorageFeatureResult(ImmutableArray<Outputs.GetVolumeGroupsV2VolumeStorageFeatureFlashModeResult> flashModes)
        {
            FlashModes = flashModes;
        }
    }
}
