// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetVpcStatusResourceCommonDomainNameServerIpListResult
    {
        /// <summary>
        /// ip address of domain name server.
        /// </summary>
        public readonly string Ip;

        [OutputConstructor]
        private GetVpcStatusResourceCommonDomainNameServerIpListResult(string ip)
        {
            Ip = ip;
        }
    }
}
