// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class ImagesV2Source
    {
        public readonly ImmutableArray<Outputs.ImagesV2SourceObjectLiteSource> ObjectLiteSources;
        public readonly ImmutableArray<Outputs.ImagesV2SourceUrlSource> UrlSources;
        public readonly ImmutableArray<Outputs.ImagesV2SourceVmDiskSource> VmDiskSources;

        [OutputConstructor]
        private ImagesV2Source(
            ImmutableArray<Outputs.ImagesV2SourceObjectLiteSource> objectLiteSources,

            ImmutableArray<Outputs.ImagesV2SourceUrlSource> urlSources,

            ImmutableArray<Outputs.ImagesV2SourceVmDiskSource> vmDiskSources)
        {
            ObjectLiteSources = objectLiteSources;
            UrlSources = urlSources;
            VmDiskSources = vmDiskSources;
        }
    }
}
