// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class OvaV2VmConfigCdRom
    {
        /// <summary>
        /// Storage provided by Nutanix ADSF
        /// </summary>
        public readonly ImmutableArray<Outputs.OvaV2VmConfigCdRomBackingInfo> BackingInfos;
        /// <summary>
        /// Virtual Machine disk (VM disk).
        /// </summary>
        public readonly ImmutableArray<Outputs.OvaV2VmConfigCdRomDiskAddress> DiskAddresses;
        public readonly string? ExtId;
        /// <summary>
        /// Type of ISO image inserted in CD-ROM. Valid values "OTHER", "GUEST_TOOLS", "GUEST_CUSTOMIZATION" .
        /// </summary>
        public readonly string? IsoType;

        [OutputConstructor]
        private OvaV2VmConfigCdRom(
            ImmutableArray<Outputs.OvaV2VmConfigCdRomBackingInfo> backingInfos,

            ImmutableArray<Outputs.OvaV2VmConfigCdRomDiskAddress> diskAddresses,

            string? extId,

            string? isoType)
        {
            BackingInfos = backingInfos;
            DiskAddresses = diskAddresses;
            ExtId = extId;
            IsoType = isoType;
        }
    }
}
