// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class OvaV2VmConfigApcConfigCpuModel
    {
        public readonly string? ExtId;
        /// <summary>
        /// -(Required) Name of the OVA.
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private OvaV2VmConfigApcConfigCpuModel(
            string? extId,

            string? name)
        {
            ExtId = extId;
            Name = name;
        }
    }
}
