// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class OvaVmDeployV2OverrideVmConfigDiskBackingInfo
    {
        public readonly ImmutableArray<Outputs.OvaVmDeployV2OverrideVmConfigDiskBackingInfoAdfsVolumeGroupReference> AdfsVolumeGroupReferences;
        /// <summary>
        /// VM disk configuration.
        /// </summary>
        public readonly ImmutableArray<Outputs.OvaVmDeployV2OverrideVmConfigDiskBackingInfoVmDisk> VmDisks;

        [OutputConstructor]
        private OvaVmDeployV2OverrideVmConfigDiskBackingInfo(
            ImmutableArray<Outputs.OvaVmDeployV2OverrideVmConfigDiskBackingInfoAdfsVolumeGroupReference> adfsVolumeGroupReferences,

            ImmutableArray<Outputs.OvaVmDeployV2OverrideVmConfigDiskBackingInfoVmDisk> vmDisks)
        {
            AdfsVolumeGroupReferences = adfsVolumeGroupReferences;
            VmDisks = vmDisks;
        }
    }
}
