// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class PcRegistrationV2NetworkInternalNetworks
    {
        public readonly Outputs.PcRegistrationV2NetworkInternalNetworksDefaultGateway DefaultGateway;
        public readonly ImmutableArray<Outputs.PcRegistrationV2NetworkInternalNetworksIpRange> IpRanges;
        public readonly Outputs.PcRegistrationV2NetworkInternalNetworksSubnetMask SubnetMask;

        [OutputConstructor]
        private PcRegistrationV2NetworkInternalNetworks(
            Outputs.PcRegistrationV2NetworkInternalNetworksDefaultGateway defaultGateway,

            ImmutableArray<Outputs.PcRegistrationV2NetworkInternalNetworksIpRange> ipRanges,

            Outputs.PcRegistrationV2NetworkInternalNetworksSubnetMask subnetMask)
        {
            DefaultGateway = defaultGateway;
            IpRanges = ipRanges;
            SubnetMask = subnetMask;
        }
    }
}
