// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class SubnetV2IpUsageIpPoolUsageRange
    {
        public readonly ImmutableArray<Outputs.SubnetV2IpUsageIpPoolUsageRangeEndIp> EndIps;
        public readonly ImmutableArray<Outputs.SubnetV2IpUsageIpPoolUsageRangeStartIp> StartIps;

        [OutputConstructor]
        private SubnetV2IpUsageIpPoolUsageRange(
            ImmutableArray<Outputs.SubnetV2IpUsageIpPoolUsageRangeEndIp> endIps,

            ImmutableArray<Outputs.SubnetV2IpUsageIpPoolUsageRangeStartIp> startIps)
        {
            EndIps = endIps;
            StartIps = startIps;
        }
    }
}
