// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class SubnetV2VirtualSwitch
    {
        /// <summary>
        /// The types of bond modes
        /// </summary>
        public readonly bool? BondMode;
        /// <summary>
        /// Cluster configuration list
        /// </summary>
        public readonly ImmutableArray<Outputs.SubnetV2VirtualSwitchCluster> Clusters;
        /// <summary>
        /// Input body to configure a Virtual Switch
        /// </summary>
        public readonly string? Description;
        public readonly string? ExtId;
        /// <summary>
        /// When true, the node is not put in maintenance mode during the create/update operation.
        /// </summary>
        public readonly bool? HasDeploymentError;
        /// <summary>
        /// Indicates whether it is a default Virtual Switch which cannot be deleted
        /// </summary>
        public readonly bool? IsDefault;
        public readonly ImmutableArray<Outputs.SubnetV2VirtualSwitchLink> Links;
        public readonly ImmutableArray<Outputs.SubnetV2VirtualSwitchMetadata> Metadatas;
        /// <summary>
        /// MTU
        /// </summary>
        public readonly int? Mtu;
        /// <summary>
        /// User-visible Virtual Switch name
        /// </summary>
        public readonly string? Name;
        public readonly string? TenantId;

        [OutputConstructor]
        private SubnetV2VirtualSwitch(
            bool? bondMode,

            ImmutableArray<Outputs.SubnetV2VirtualSwitchCluster> clusters,

            string? description,

            string? extId,

            bool? hasDeploymentError,

            bool? isDefault,

            ImmutableArray<Outputs.SubnetV2VirtualSwitchLink> links,

            ImmutableArray<Outputs.SubnetV2VirtualSwitchMetadata> metadatas,

            int? mtu,

            string? name,

            string? tenantId)
        {
            BondMode = bondMode;
            Clusters = clusters;
            Description = description;
            ExtId = extId;
            HasDeploymentError = hasDeploymentError;
            IsDefault = isDefault;
            Links = links;
            Metadatas = metadatas;
            Mtu = mtu;
            Name = name;
            TenantId = tenantId;
        }
    }
}
