// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class VmCdromInsertEjectV2BackingInfoDataSourceReferenceVmDiskReference
    {
        public readonly ImmutableArray<Outputs.VmCdromInsertEjectV2BackingInfoDataSourceReferenceVmDiskReferenceDiskAddress> DiskAddresses;
        public readonly string? DiskExtId;
        public readonly ImmutableArray<Outputs.VmCdromInsertEjectV2BackingInfoDataSourceReferenceVmDiskReferenceVmReference> VmReferences;

        [OutputConstructor]
        private VmCdromInsertEjectV2BackingInfoDataSourceReferenceVmDiskReference(
            ImmutableArray<Outputs.VmCdromInsertEjectV2BackingInfoDataSourceReferenceVmDiskReferenceDiskAddress> diskAddresses,

            string? diskExtId,

            ImmutableArray<Outputs.VmCdromInsertEjectV2BackingInfoDataSourceReferenceVmDiskReferenceVmReference> vmReferences)
        {
            DiskAddresses = diskAddresses;
            DiskExtId = diskExtId;
            VmReferences = vmReferences;
        }
    }
}
