// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Outputs
{

    [OutputType]
    public sealed class VmCloneV2CdRomBackingInfoDataSourceReferenceVmDiskReferenceVmReference
    {
        /// <summary>
        /// - (Optional) The globally unique identifier of a VM. It should be of type UUID.
        /// </summary>
        public readonly string? ExtId;

        [OutputConstructor]
        private VmCloneV2CdRomBackingInfoDataSourceReferenceVmDiskReferenceVmReference(string? extId)
        {
            ExtId = extId;
        }
    }
}
