# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetClusterProfilesV2Result',
    'AwaitableGetClusterProfilesV2Result',
    'get_cluster_profiles_v2',
    'get_cluster_profiles_v2_output',
]

@pulumi.output_type
class GetClusterProfilesV2Result:
    """
    A collection of values returned by getClusterProfilesV2.
    """
    def __init__(__self__, cluster_profiles=None, filter=None, id=None, limit=None, order_by=None, page=None, select=None):
        if cluster_profiles and not isinstance(cluster_profiles, list):
            raise TypeError("Expected argument 'cluster_profiles' to be a list")
        pulumi.set(__self__, "cluster_profiles", cluster_profiles)
        if filter and not isinstance(filter, str):
            raise TypeError("Expected argument 'filter' to be a str")
        pulumi.set(__self__, "filter", filter)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if limit and not isinstance(limit, int):
            raise TypeError("Expected argument 'limit' to be a int")
        pulumi.set(__self__, "limit", limit)
        if order_by and not isinstance(order_by, str):
            raise TypeError("Expected argument 'order_by' to be a str")
        pulumi.set(__self__, "order_by", order_by)
        if page and not isinstance(page, int):
            raise TypeError("Expected argument 'page' to be a int")
        pulumi.set(__self__, "page", page)
        if select and not isinstance(select, str):
            raise TypeError("Expected argument 'select' to be a str")
        pulumi.set(__self__, "select", select)

    @_builtins.property
    @pulumi.getter(name="clusterProfiles")
    def cluster_profiles(self) -> Sequence['outputs.GetClusterProfilesV2ClusterProfileResult']:
        """
        - List of cluster profiles.
        """
        return pulumi.get(self, "cluster_profiles")

    @_builtins.property
    @pulumi.getter
    def filter(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "filter")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def limit(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "limit")

    @_builtins.property
    @pulumi.getter(name="orderBy")
    def order_by(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "order_by")

    @_builtins.property
    @pulumi.getter
    def page(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "page")

    @_builtins.property
    @pulumi.getter
    def select(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "select")


class AwaitableGetClusterProfilesV2Result(GetClusterProfilesV2Result):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetClusterProfilesV2Result(
            cluster_profiles=self.cluster_profiles,
            filter=self.filter,
            id=self.id,
            limit=self.limit,
            order_by=self.order_by,
            page=self.page,
            select=self.select)


def get_cluster_profiles_v2(filter: Optional[_builtins.str] = None,
                            limit: Optional[_builtins.int] = None,
                            order_by: Optional[_builtins.str] = None,
                            page: Optional[_builtins.int] = None,
                            select: Optional[_builtins.str] = None,
                            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetClusterProfilesV2Result:
    """
    Fetches a list of cluster profile entities. A profile consists of different cluster settings like Network Time Protocol(NTP), Domain Name System(DNS), and so on.

    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_nutanix as nutanix

    list_cluster_profiles = nutanix.get_cluster_profile_v2()
    filtered_cluster_profiles = nutanix.get_cluster_profiles_v2(filter="clusterCount eq 62")
    paged_cluster_profiles = nutanix.get_cluster_profiles_v2(page=1,
        limit=10)
    ordered_cluster_profiles = nutanix.get_cluster_profiles_v2(order_by="name")
    selected_cluster_profiles = nutanix.get_cluster_profiles_v2(select="name,description")
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.str filter: A URL query parameter that allows clients to filter a collection of resources. The expression specified with \\$filter is evaluated for each resource in the collection, and only items where the expression evaluates to true are included in the response. Expression specified with the \\$filter must conform to the OData V4.01 URL conventions. The filter can be applied to the following fields:
           * clusterCount : `filter="clusterCount eq 62"`
           * createTime : `filter="createTime eq '2009-09-23T14:30:00-07:00'"`
           * createdBy : `filter="createdBy eq '984ff444-b6aa-4fa9-a8bd-37ef221cf1b0'"`
           * driftedClusterCount : `filter="driftedClusterCount eq 3"`
           * lastUpdateTime : `filter="lastUpdateTime eq '2009-09-23T14:30:00-07:00'"`
           * lastUpdatedBy : `filter="lastUpdatedBy eq '6debfc73-b4a9-4d68-a702-f0cfc1d721fb'"`
           * name : `filter="name eq 'Test Cluster Profile'"`
    :param _builtins.int limit: A URL query parameter that specifies the total number of records returned in the result set. Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set.
    :param _builtins.str order_by: A URL query parameter that allows clients to specify the sort criteria for the returned list of objects. Resources can be sorted in ascending order using asc or descending order using desc. If asc or desc are not specified, the resources will be sorted in ascending order by default. The orderby can be applied to the following fields:
           * clusterCount : `orderby="clusterCount"`
           * createTime : `orderby="createTime desc"`
           * createdBy : `orderby="createdBy desc"`
           * driftedClusterCount : `orderby="driftedClusterCount desc"`
           * lastUpdateTime : `orderby="lastUpdateTime desc"`
           * lastUpdatedBy : `orderby="lastUpdatedBy desc"`
           * name : `orderby="name desc"`
    :param _builtins.int page: A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results.
    :param _builtins.str select: A URL query parameter that allows clients to request a specific set of properties for each entity or complex type. Expression specified with the \\$select must conform to the OData V4.01 URL conventions. If a \\$select expression consists of a single select item that is an asterisk (i.e., *), then all properties on the matching resource will be returned.
           
           The following selection keys are supported:
           
           * allowedOverrides : `select="allowedOverrides"`
           * clusterCount : `select="clusterCount"`
           * clusters : `select="clusters"`
           * createTime : `select="createTime"`
           * createdBy : `select="createdBy"`
           * description : `select="description"`
           * driftedClusterCount : `select="driftedClusterCount"`
           * extId : `select="extId"`
           * lastUpdateTime : `select="lastUpdateTime"`
           * lastUpdatedBy : `select="lastUpdatedBy"`
           * links : `select="links"`
           * name : `select="name"`
           * nameServerIpList : `select="nameServerIpList"`
           * nfsSubnetWhitelist : `select="nfsSubnetWhitelist"`
           * ntpServerIpList : `select="ntpServerIpList"`
           * pulseStatus : `select="pulseStatus"`
           * rsyslogServerList : `select="rsyslogServerList"`
           * smtpServer : `select="smtpServer"`
           * snmpConfig : `select="snmpConfig"`
           * tenantId : `select="tenantId"`
    """
    __args__ = dict()
    __args__['filter'] = filter
    __args__['limit'] = limit
    __args__['orderBy'] = order_by
    __args__['page'] = page
    __args__['select'] = select
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('nutanix:index/getClusterProfilesV2:getClusterProfilesV2', __args__, opts=opts, typ=GetClusterProfilesV2Result).value

    return AwaitableGetClusterProfilesV2Result(
        cluster_profiles=pulumi.get(__ret__, 'cluster_profiles'),
        filter=pulumi.get(__ret__, 'filter'),
        id=pulumi.get(__ret__, 'id'),
        limit=pulumi.get(__ret__, 'limit'),
        order_by=pulumi.get(__ret__, 'order_by'),
        page=pulumi.get(__ret__, 'page'),
        select=pulumi.get(__ret__, 'select'))
def get_cluster_profiles_v2_output(filter: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                   limit: pulumi.Input[Optional[Optional[_builtins.int]]] = None,
                                   order_by: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                   page: pulumi.Input[Optional[Optional[_builtins.int]]] = None,
                                   select: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                   opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetClusterProfilesV2Result]:
    """
    Fetches a list of cluster profile entities. A profile consists of different cluster settings like Network Time Protocol(NTP), Domain Name System(DNS), and so on.

    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_nutanix as nutanix

    list_cluster_profiles = nutanix.get_cluster_profile_v2()
    filtered_cluster_profiles = nutanix.get_cluster_profiles_v2(filter="clusterCount eq 62")
    paged_cluster_profiles = nutanix.get_cluster_profiles_v2(page=1,
        limit=10)
    ordered_cluster_profiles = nutanix.get_cluster_profiles_v2(order_by="name")
    selected_cluster_profiles = nutanix.get_cluster_profiles_v2(select="name,description")
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.str filter: A URL query parameter that allows clients to filter a collection of resources. The expression specified with \\$filter is evaluated for each resource in the collection, and only items where the expression evaluates to true are included in the response. Expression specified with the \\$filter must conform to the OData V4.01 URL conventions. The filter can be applied to the following fields:
           * clusterCount : `filter="clusterCount eq 62"`
           * createTime : `filter="createTime eq '2009-09-23T14:30:00-07:00'"`
           * createdBy : `filter="createdBy eq '984ff444-b6aa-4fa9-a8bd-37ef221cf1b0'"`
           * driftedClusterCount : `filter="driftedClusterCount eq 3"`
           * lastUpdateTime : `filter="lastUpdateTime eq '2009-09-23T14:30:00-07:00'"`
           * lastUpdatedBy : `filter="lastUpdatedBy eq '6debfc73-b4a9-4d68-a702-f0cfc1d721fb'"`
           * name : `filter="name eq 'Test Cluster Profile'"`
    :param _builtins.int limit: A URL query parameter that specifies the total number of records returned in the result set. Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set.
    :param _builtins.str order_by: A URL query parameter that allows clients to specify the sort criteria for the returned list of objects. Resources can be sorted in ascending order using asc or descending order using desc. If asc or desc are not specified, the resources will be sorted in ascending order by default. The orderby can be applied to the following fields:
           * clusterCount : `orderby="clusterCount"`
           * createTime : `orderby="createTime desc"`
           * createdBy : `orderby="createdBy desc"`
           * driftedClusterCount : `orderby="driftedClusterCount desc"`
           * lastUpdateTime : `orderby="lastUpdateTime desc"`
           * lastUpdatedBy : `orderby="lastUpdatedBy desc"`
           * name : `orderby="name desc"`
    :param _builtins.int page: A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results.
    :param _builtins.str select: A URL query parameter that allows clients to request a specific set of properties for each entity or complex type. Expression specified with the \\$select must conform to the OData V4.01 URL conventions. If a \\$select expression consists of a single select item that is an asterisk (i.e., *), then all properties on the matching resource will be returned.
           
           The following selection keys are supported:
           
           * allowedOverrides : `select="allowedOverrides"`
           * clusterCount : `select="clusterCount"`
           * clusters : `select="clusters"`
           * createTime : `select="createTime"`
           * createdBy : `select="createdBy"`
           * description : `select="description"`
           * driftedClusterCount : `select="driftedClusterCount"`
           * extId : `select="extId"`
           * lastUpdateTime : `select="lastUpdateTime"`
           * lastUpdatedBy : `select="lastUpdatedBy"`
           * links : `select="links"`
           * name : `select="name"`
           * nameServerIpList : `select="nameServerIpList"`
           * nfsSubnetWhitelist : `select="nfsSubnetWhitelist"`
           * ntpServerIpList : `select="ntpServerIpList"`
           * pulseStatus : `select="pulseStatus"`
           * rsyslogServerList : `select="rsyslogServerList"`
           * smtpServer : `select="smtpServer"`
           * snmpConfig : `select="snmpConfig"`
           * tenantId : `select="tenantId"`
    """
    __args__ = dict()
    __args__['filter'] = filter
    __args__['limit'] = limit
    __args__['orderBy'] = order_by
    __args__['page'] = page
    __args__['select'] = select
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('nutanix:index/getClusterProfilesV2:getClusterProfilesV2', __args__, opts=opts, typ=GetClusterProfilesV2Result)
    return __ret__.apply(lambda __response__: GetClusterProfilesV2Result(
        cluster_profiles=pulumi.get(__response__, 'cluster_profiles'),
        filter=pulumi.get(__response__, 'filter'),
        id=pulumi.get(__response__, 'id'),
        limit=pulumi.get(__response__, 'limit'),
        order_by=pulumi.get(__response__, 'order_by'),
        page=pulumi.get(__response__, 'page'),
        select=pulumi.get(__response__, 'select')))
