# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetIamEntitiesV2Result',
    'AwaitableGetIamEntitiesV2Result',
    'get_iam_entities_v2',
    'get_iam_entities_v2_output',
]

@pulumi.output_type
class GetIamEntitiesV2Result:
    """
    A collection of values returned by getIamEntitiesV2.
    """
    def __init__(__self__, entities=None, filter=None, id=None, limit=None, order_by=None, page=None, select=None):
        if entities and not isinstance(entities, list):
            raise TypeError("Expected argument 'entities' to be a list")
        pulumi.set(__self__, "entities", entities)
        if filter and not isinstance(filter, str):
            raise TypeError("Expected argument 'filter' to be a str")
        pulumi.set(__self__, "filter", filter)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if limit and not isinstance(limit, int):
            raise TypeError("Expected argument 'limit' to be a int")
        pulumi.set(__self__, "limit", limit)
        if order_by and not isinstance(order_by, str):
            raise TypeError("Expected argument 'order_by' to be a str")
        pulumi.set(__self__, "order_by", order_by)
        if page and not isinstance(page, int):
            raise TypeError("Expected argument 'page' to be a int")
        pulumi.set(__self__, "page", page)
        if select and not isinstance(select, str):
            raise TypeError("Expected argument 'select' to be a str")
        pulumi.set(__self__, "select", select)

    @_builtins.property
    @pulumi.getter
    def entities(self) -> Sequence['outputs.GetIamEntitiesV2EntityResult']:
        """
        List of IAM entities.
        """
        return pulumi.get(self, "entities")

    @_builtins.property
    @pulumi.getter
    def filter(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "filter")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def limit(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "limit")

    @_builtins.property
    @pulumi.getter(name="orderBy")
    def order_by(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "order_by")

    @_builtins.property
    @pulumi.getter
    def page(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "page")

    @_builtins.property
    @pulumi.getter
    def select(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "select")


class AwaitableGetIamEntitiesV2Result(GetIamEntitiesV2Result):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetIamEntitiesV2Result(
            entities=self.entities,
            filter=self.filter,
            id=self.id,
            limit=self.limit,
            order_by=self.order_by,
            page=self.page,
            select=self.select)


def get_iam_entities_v2(filter: Optional[_builtins.str] = None,
                        limit: Optional[_builtins.int] = None,
                        order_by: Optional[_builtins.str] = None,
                        page: Optional[_builtins.int] = None,
                        select: Optional[_builtins.str] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetIamEntitiesV2Result:
    """
    Provides a datasource to list IAM Entities. Entities are used in authorization policies (e.g. user, role, cluster). Supports pagination and OData <span pulumi-lang-nodejs="`filter`" pulumi-lang-dotnet="`Filter`" pulumi-lang-go="`filter`" pulumi-lang-python="`filter`" pulumi-lang-yaml="`filter`" pulumi-lang-java="`filter`" pulumi-lang-hcl="`filter`">`filter`</span>, <span pulumi-lang-nodejs="`orderBy`" pulumi-lang-dotnet="`OrderBy`" pulumi-lang-go="`orderBy`" pulumi-lang-python="`order_by`" pulumi-lang-yaml="`orderBy`" pulumi-lang-java="`orderBy`" pulumi-lang-hcl="`order_by`">`orderBy`</span>, and <span pulumi-lang-nodejs="`select`" pulumi-lang-dotnet="`Select`" pulumi-lang-go="`select`" pulumi-lang-python="`select`" pulumi-lang-yaml="`select`" pulumi-lang-java="`select`" pulumi-lang-hcl="`select`">`select`</span>.

    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_nutanix as nutanix

    # List all entities (default page/limit)
    all = nutanix.get_iam_entities_v2()
    # List entities with filter and pagination
    filtered = nutanix.get_iam_entities_v2(filter="name eq 'user'",
        limit=20,
        page=0)
    # List with order_by
    ordered = nutanix.get_iam_entities_v2(order_by="name asc",
        limit=50)
    # List with select to specify returned fields
    selected = nutanix.get_iam_entities_v2(select="name,displayName,extId",
        limit=10)
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.str filter: OData filter expression. The filter can be applied to the following fields:
           * `createdBy` - Filter by creator (user or service ext_id).
           * `createdTime` - Filter by creation time (ISO 8601 format).
           * `displayName` - Filter by display name.
           * `extId` - Filter by entity external identifier.
           * `lastUpdatedTime` - Filter by last updated time (ISO 8601 format).
    :param _builtins.int limit: Number of records to return. Must be between 1 and 100. Default is 50.
    :param _builtins.str order_by: OData orderby expression. The orderby can be applied to the following fields:
           
           * `createdTime` - Sort by creation time (ISO 8601 format).
           * `displayName` - Sort by display name.
           * `extId` - Sort by entity external identifier.
           * `lastUpdatedTime` - Sort by last updated time (ISO 8601 format).
    :param _builtins.int page: Page number of the result set (0-based). Must be between 0 and the maximum number of pages.
    :param _builtins.str select: OData select expression. The select can be applied to the following fields:
           * `clientName` - Select by client name.
           * `createdBy` - Select by creator (user or service ext_id).
           * `createdTime` - Select by creation time (ISO 8601 format).
    """
    __args__ = dict()
    __args__['filter'] = filter
    __args__['limit'] = limit
    __args__['orderBy'] = order_by
    __args__['page'] = page
    __args__['select'] = select
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('nutanix:index/getIamEntitiesV2:getIamEntitiesV2', __args__, opts=opts, typ=GetIamEntitiesV2Result).value

    return AwaitableGetIamEntitiesV2Result(
        entities=pulumi.get(__ret__, 'entities'),
        filter=pulumi.get(__ret__, 'filter'),
        id=pulumi.get(__ret__, 'id'),
        limit=pulumi.get(__ret__, 'limit'),
        order_by=pulumi.get(__ret__, 'order_by'),
        page=pulumi.get(__ret__, 'page'),
        select=pulumi.get(__ret__, 'select'))
def get_iam_entities_v2_output(filter: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                               limit: Optional[pulumi.Input[Optional[_builtins.int]]] = None,
                               order_by: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                               page: Optional[pulumi.Input[Optional[_builtins.int]]] = None,
                               select: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetIamEntitiesV2Result]:
    """
    Provides a datasource to list IAM Entities. Entities are used in authorization policies (e.g. user, role, cluster). Supports pagination and OData <span pulumi-lang-nodejs="`filter`" pulumi-lang-dotnet="`Filter`" pulumi-lang-go="`filter`" pulumi-lang-python="`filter`" pulumi-lang-yaml="`filter`" pulumi-lang-java="`filter`" pulumi-lang-hcl="`filter`">`filter`</span>, <span pulumi-lang-nodejs="`orderBy`" pulumi-lang-dotnet="`OrderBy`" pulumi-lang-go="`orderBy`" pulumi-lang-python="`order_by`" pulumi-lang-yaml="`orderBy`" pulumi-lang-java="`orderBy`" pulumi-lang-hcl="`order_by`">`orderBy`</span>, and <span pulumi-lang-nodejs="`select`" pulumi-lang-dotnet="`Select`" pulumi-lang-go="`select`" pulumi-lang-python="`select`" pulumi-lang-yaml="`select`" pulumi-lang-java="`select`" pulumi-lang-hcl="`select`">`select`</span>.

    ## Example Usage

    <!--Start PulumiCodeChooser -->
    ```python
    import pulumi
    import pulumi_nutanix as nutanix

    # List all entities (default page/limit)
    all = nutanix.get_iam_entities_v2()
    # List entities with filter and pagination
    filtered = nutanix.get_iam_entities_v2(filter="name eq 'user'",
        limit=20,
        page=0)
    # List with order_by
    ordered = nutanix.get_iam_entities_v2(order_by="name asc",
        limit=50)
    # List with select to specify returned fields
    selected = nutanix.get_iam_entities_v2(select="name,displayName,extId",
        limit=10)
    ```
    <!--End PulumiCodeChooser -->


    :param _builtins.str filter: OData filter expression. The filter can be applied to the following fields:
           * `createdBy` - Filter by creator (user or service ext_id).
           * `createdTime` - Filter by creation time (ISO 8601 format).
           * `displayName` - Filter by display name.
           * `extId` - Filter by entity external identifier.
           * `lastUpdatedTime` - Filter by last updated time (ISO 8601 format).
    :param _builtins.int limit: Number of records to return. Must be between 1 and 100. Default is 50.
    :param _builtins.str order_by: OData orderby expression. The orderby can be applied to the following fields:
           
           * `createdTime` - Sort by creation time (ISO 8601 format).
           * `displayName` - Sort by display name.
           * `extId` - Sort by entity external identifier.
           * `lastUpdatedTime` - Sort by last updated time (ISO 8601 format).
    :param _builtins.int page: Page number of the result set (0-based). Must be between 0 and the maximum number of pages.
    :param _builtins.str select: OData select expression. The select can be applied to the following fields:
           * `clientName` - Select by client name.
           * `createdBy` - Select by creator (user or service ext_id).
           * `createdTime` - Select by creation time (ISO 8601 format).
    """
    __args__ = dict()
    __args__['filter'] = filter
    __args__['limit'] = limit
    __args__['orderBy'] = order_by
    __args__['page'] = page
    __args__['select'] = select
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('nutanix:index/getIamEntitiesV2:getIamEntitiesV2', __args__, opts=opts, typ=GetIamEntitiesV2Result)
    return __ret__.apply(lambda __response__: GetIamEntitiesV2Result(
        entities=pulumi.get(__response__, 'entities'),
        filter=pulumi.get(__response__, 'filter'),
        id=pulumi.get(__response__, 'id'),
        limit=pulumi.get(__response__, 'limit'),
        order_by=pulumi.get(__response__, 'order_by'),
        page=pulumi.get(__response__, 'page'),
        select=pulumi.get(__response__, 'select')))
