// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nutanix

import (
	"context"
	"reflect"

	"github.com/pierskarsenbarg/pulumi-nutanix/sdk/go/nutanix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Discovers and lists Nutanix-imaged nodes within an IPv6 network.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pierskarsenbarg/pulumi-nutanix/sdk/go/nutanix"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := nutanix.GetFoundationDiscoverNodes(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetFoundationDiscoverNodes(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetFoundationDiscoverNodesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetFoundationDiscoverNodesResult
	err := ctx.Invoke("nutanix:index/getFoundationDiscoverNodes:getFoundationDiscoverNodes", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getFoundationDiscoverNodes.
type GetFoundationDiscoverNodesResult struct {
	// List of Nutanix-imaged nodes within an IPv6 network
	Entities []GetFoundationDiscoverNodesEntity `pulumi:"entities"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}

func GetFoundationDiscoverNodesOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetFoundationDiscoverNodesResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetFoundationDiscoverNodesResult, error) {
		r, err := GetFoundationDiscoverNodes(ctx, opts...)
		var s GetFoundationDiscoverNodesResult
		if r != nil {
			s = *r
		}
		return s, err
	}).(GetFoundationDiscoverNodesResultOutput)
}

// A collection of values returned by getFoundationDiscoverNodes.
type GetFoundationDiscoverNodesResultOutput struct{ *pulumi.OutputState }

func (GetFoundationDiscoverNodesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFoundationDiscoverNodesResult)(nil)).Elem()
}

func (o GetFoundationDiscoverNodesResultOutput) ToGetFoundationDiscoverNodesResultOutput() GetFoundationDiscoverNodesResultOutput {
	return o
}

func (o GetFoundationDiscoverNodesResultOutput) ToGetFoundationDiscoverNodesResultOutputWithContext(ctx context.Context) GetFoundationDiscoverNodesResultOutput {
	return o
}

// List of Nutanix-imaged nodes within an IPv6 network
func (o GetFoundationDiscoverNodesResultOutput) Entities() GetFoundationDiscoverNodesEntityArrayOutput {
	return o.ApplyT(func(v GetFoundationDiscoverNodesResult) []GetFoundationDiscoverNodesEntity { return v.Entities }).(GetFoundationDiscoverNodesEntityArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetFoundationDiscoverNodesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetFoundationDiscoverNodesResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetFoundationDiscoverNodesResultOutput{})
}
