// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nutanix

import (
	"context"
	"reflect"

	"github.com/pierskarsenbarg/pulumi-nutanix/sdk/go/nutanix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides Nutanix resource to create storage policy
//
// > **Note**:
// Once <span pulumi-lang-nodejs="`encryptionState`" pulumi-lang-dotnet="`EncryptionState`" pulumi-lang-go="`encryptionState`" pulumi-lang-python="`encryption_state`" pulumi-lang-yaml="`encryptionState`" pulumi-lang-java="`encryptionState`" pulumi-lang-hcl="`encryption_state`">`encryptionState`</span> is explicitly set to `ENABLED`, it cannot be reverted back to a system-derived value.
//
// If compression_state, encryption_state, or<span pulumi-lang-nodejs=" replicationFactor " pulumi-lang-dotnet=" ReplicationFactor " pulumi-lang-go=" replicationFactor " pulumi-lang-python=" replication_factor " pulumi-lang-yaml=" replicationFactor " pulumi-lang-java=" replicationFactor " pulumi-lang-hcl=" replication_factor "> replicationFactor </span>are intended to be system-derived, ensure that the<span pulumi-lang-nodejs=" qosSpec " pulumi-lang-dotnet=" QosSpec " pulumi-lang-go=" qosSpec " pulumi-lang-python=" qos_spec " pulumi-lang-yaml=" qosSpec " pulumi-lang-java=" qosSpec " pulumi-lang-hcl=" qos_spec "> qosSpec </span>block is included.
//
// ## Example
//
// ### Complete Example with All Fields
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/pierskarsenbarg/pulumi-nutanix/sdk/go/nutanix"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := nutanix.NewStoragePolicyV2(ctx, "example", &nutanix.StoragePolicyV2Args{
//				Name: pulumi.String("my-storage-policy"),
//				CompressionSpecs: nutanix.StoragePolicyV2CompressionSpecArray{
//					&nutanix.StoragePolicyV2CompressionSpecArgs{
//						CompressionState: pulumi.String("POSTPROCESS"),
//					},
//				},
//				EncryptionSpecs: nutanix.StoragePolicyV2EncryptionSpecArray{
//					&nutanix.StoragePolicyV2EncryptionSpecArgs{
//						EncryptionState: pulumi.String("ENABLED"),
//					},
//				},
//				QosSpecs: nutanix.StoragePolicyV2QosSpecArray{
//					&nutanix.StoragePolicyV2QosSpecArgs{
//						ThrottledIops: pulumi.Int(1000),
//					},
//				},
//				FaultToleranceSpecs: nutanix.StoragePolicyV2FaultToleranceSpecArray{
//					&nutanix.StoragePolicyV2FaultToleranceSpecArgs{
//						ReplicationFactor: pulumi.String("THREE"),
//					},
//				},
//				CategoryExtIds: pulumi.StringArray{
//					pulumi.String("4d552748-e119-540a-b06c-3c6f0d213fa2"),
//					pulumi.String("5e663859-f220-651b-c17d-4d7f0e324fb3"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ### Minimal Example with System-Derived Values
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/pierskarsenbarg/pulumi-nutanix/sdk/go/nutanix"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := nutanix.NewStoragePolicyV2(ctx, "minimal", &nutanix.StoragePolicyV2Args{
//				Name: pulumi.String("minimal-storage-policy"),
//				QosSpecs: nutanix.StoragePolicyV2QosSpecArray{
//					&nutanix.StoragePolicyV2QosSpecArgs{
//						ThrottledIops: pulumi.Int(100),
//					},
//				},
//				CompressionSpecs: nutanix.StoragePolicyV2CompressionSpecArray{
//					&nutanix.StoragePolicyV2CompressionSpecArgs{
//						CompressionState: pulumi.String("SYSTEM_DERIVED"),
//					},
//				},
//				EncryptionSpecs: nutanix.StoragePolicyV2EncryptionSpecArray{
//					&nutanix.StoragePolicyV2EncryptionSpecArgs{
//						EncryptionState: pulumi.String("SYSTEM_DERIVED"),
//					},
//				},
//				FaultToleranceSpecs: nutanix.StoragePolicyV2FaultToleranceSpecArray{
//					&nutanix.StoragePolicyV2FaultToleranceSpecArgs{
//						ReplicationFactor: pulumi.String("SYSTEM_DERIVED"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ### Example with Inline Compression
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/pierskarsenbarg/pulumi-nutanix/sdk/go/nutanix"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := nutanix.NewStoragePolicyV2(ctx, "inline_compression", &nutanix.StoragePolicyV2Args{
//				Name: pulumi.String("inline-compression-policy"),
//				CompressionSpecs: nutanix.StoragePolicyV2CompressionSpecArray{
//					&nutanix.StoragePolicyV2CompressionSpecArgs{
//						CompressionState: pulumi.String("INLINE"),
//					},
//				},
//				EncryptionSpecs: nutanix.StoragePolicyV2EncryptionSpecArray{
//					&nutanix.StoragePolicyV2EncryptionSpecArgs{
//						EncryptionState: pulumi.String("ENABLED"),
//					},
//				},
//				QosSpecs: nutanix.StoragePolicyV2QosSpecArray{
//					&nutanix.StoragePolicyV2QosSpecArgs{
//						ThrottledIops: pulumi.Int(5000),
//					},
//				},
//				FaultToleranceSpecs: nutanix.StoragePolicyV2FaultToleranceSpecArray{
//					&nutanix.StoragePolicyV2FaultToleranceSpecArgs{
//						ReplicationFactor: pulumi.String("TWO"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ### Example with Disabled Compression
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/pierskarsenbarg/pulumi-nutanix/sdk/go/nutanix"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := nutanix.NewStoragePolicyV2(ctx, "no_compression", &nutanix.StoragePolicyV2Args{
//				Name: pulumi.String("no-compression-policy"),
//				CompressionSpecs: nutanix.StoragePolicyV2CompressionSpecArray{
//					&nutanix.StoragePolicyV2CompressionSpecArgs{
//						CompressionState: pulumi.String("DISABLED"),
//					},
//				},
//				QosSpecs: nutanix.StoragePolicyV2QosSpecArray{
//					&nutanix.StoragePolicyV2QosSpecArgs{
//						ThrottledIops: pulumi.Int(2000),
//					},
//				},
//				FaultToleranceSpecs: nutanix.StoragePolicyV2FaultToleranceSpecArray{
//					&nutanix.StoragePolicyV2FaultToleranceSpecArgs{
//						ReplicationFactor: pulumi.String("THREE"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ### Example with Categories Only
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/pierskarsenbarg/pulumi-nutanix/sdk/go/nutanix"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Rest all will be System Derived
//			_, err := nutanix.NewStoragePolicyV2(ctx, "categorized", &nutanix.StoragePolicyV2Args{
//				Name: pulumi.String("categorized-policy"),
//				CategoryExtIds: pulumi.StringArray{
//					pulumi.String("4d552748-e119-540a-b06c-3c6f0d213fa2"),
//				},
//				QosSpecs: nutanix.StoragePolicyV2QosSpecArray{
//					&nutanix.StoragePolicyV2QosSpecArgs{
//						ThrottledIops: pulumi.Int(100),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
type StoragePolicyV2 struct {
	pulumi.CustomResourceState

	// - (Optional) List of external identifiers for Categories to be included in the Storage Policy. Each ID must be a valid UUID format. Maximum 20 items allowed.
	CategoryExtIds pulumi.StringArrayOutput `pulumi:"categoryExtIds"`
	// - (Optional) Defines compression parameters for entities governed by the Storage Policy.
	CompressionSpecs StoragePolicyV2CompressionSpecArrayOutput `pulumi:"compressionSpecs"`
	// - (Optional) Defines encryption parameters for entities governed by the Storage Policy.
	EncryptionSpecs StoragePolicyV2EncryptionSpecArrayOutput `pulumi:"encryptionSpecs"`
	// - (Computed) External identifier of the Storage Policy.
	ExtId pulumi.StringOutput `pulumi:"extId"`
	// - (Optional) Defines Fault Tolerance parameters for the entities.
	FaultToleranceSpecs StoragePolicyV2FaultToleranceSpecArrayOutput `pulumi:"faultToleranceSpecs"`
	// - A HATEOAS style link for the response. Each link contains a user-friendly name identifying the link and an address for retrieving the particular resource.
	Links StoragePolicyV2LinkArrayOutput `pulumi:"links"`
	// - (Required) Storage Policy name. Must be unique and cannot exceed 64 characters.
	Name pulumi.StringOutput `pulumi:"name"`
	// - (Computed) Indicates whether the policy is user-created or system-created. Valid values: `"USER"`, `"SYSTEM"`.
	PolicyType pulumi.StringOutput `pulumi:"policyType"`
	// - (Optional) Defines Storage Quality of Service (QOS) parameters for the entities.
	QosSpecs StoragePolicyV2QosSpecArrayOutput `pulumi:"qosSpecs"`
	// - A globally unique identifier that represents the tenant that owns this entity.
	TenantId pulumi.StringOutput `pulumi:"tenantId"`
}

// NewStoragePolicyV2 registers a new resource with the given unique name, arguments, and options.
func NewStoragePolicyV2(ctx *pulumi.Context,
	name string, args *StoragePolicyV2Args, opts ...pulumi.ResourceOption) (*StoragePolicyV2, error) {
	if args == nil {
		args = &StoragePolicyV2Args{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource StoragePolicyV2
	err := ctx.RegisterResource("nutanix:index/storagePolicyV2:StoragePolicyV2", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetStoragePolicyV2 gets an existing StoragePolicyV2 resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetStoragePolicyV2(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *StoragePolicyV2State, opts ...pulumi.ResourceOption) (*StoragePolicyV2, error) {
	var resource StoragePolicyV2
	err := ctx.ReadResource("nutanix:index/storagePolicyV2:StoragePolicyV2", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering StoragePolicyV2 resources.
type storagePolicyV2State struct {
	// - (Optional) List of external identifiers for Categories to be included in the Storage Policy. Each ID must be a valid UUID format. Maximum 20 items allowed.
	CategoryExtIds []string `pulumi:"categoryExtIds"`
	// - (Optional) Defines compression parameters for entities governed by the Storage Policy.
	CompressionSpecs []StoragePolicyV2CompressionSpec `pulumi:"compressionSpecs"`
	// - (Optional) Defines encryption parameters for entities governed by the Storage Policy.
	EncryptionSpecs []StoragePolicyV2EncryptionSpec `pulumi:"encryptionSpecs"`
	// - (Computed) External identifier of the Storage Policy.
	ExtId *string `pulumi:"extId"`
	// - (Optional) Defines Fault Tolerance parameters for the entities.
	FaultToleranceSpecs []StoragePolicyV2FaultToleranceSpec `pulumi:"faultToleranceSpecs"`
	// - A HATEOAS style link for the response. Each link contains a user-friendly name identifying the link and an address for retrieving the particular resource.
	Links []StoragePolicyV2Link `pulumi:"links"`
	// - (Required) Storage Policy name. Must be unique and cannot exceed 64 characters.
	Name *string `pulumi:"name"`
	// - (Computed) Indicates whether the policy is user-created or system-created. Valid values: `"USER"`, `"SYSTEM"`.
	PolicyType *string `pulumi:"policyType"`
	// - (Optional) Defines Storage Quality of Service (QOS) parameters for the entities.
	QosSpecs []StoragePolicyV2QosSpec `pulumi:"qosSpecs"`
	// - A globally unique identifier that represents the tenant that owns this entity.
	TenantId *string `pulumi:"tenantId"`
}

type StoragePolicyV2State struct {
	// - (Optional) List of external identifiers for Categories to be included in the Storage Policy. Each ID must be a valid UUID format. Maximum 20 items allowed.
	CategoryExtIds pulumi.StringArrayInput
	// - (Optional) Defines compression parameters for entities governed by the Storage Policy.
	CompressionSpecs StoragePolicyV2CompressionSpecArrayInput
	// - (Optional) Defines encryption parameters for entities governed by the Storage Policy.
	EncryptionSpecs StoragePolicyV2EncryptionSpecArrayInput
	// - (Computed) External identifier of the Storage Policy.
	ExtId pulumi.StringPtrInput
	// - (Optional) Defines Fault Tolerance parameters for the entities.
	FaultToleranceSpecs StoragePolicyV2FaultToleranceSpecArrayInput
	// - A HATEOAS style link for the response. Each link contains a user-friendly name identifying the link and an address for retrieving the particular resource.
	Links StoragePolicyV2LinkArrayInput
	// - (Required) Storage Policy name. Must be unique and cannot exceed 64 characters.
	Name pulumi.StringPtrInput
	// - (Computed) Indicates whether the policy is user-created or system-created. Valid values: `"USER"`, `"SYSTEM"`.
	PolicyType pulumi.StringPtrInput
	// - (Optional) Defines Storage Quality of Service (QOS) parameters for the entities.
	QosSpecs StoragePolicyV2QosSpecArrayInput
	// - A globally unique identifier that represents the tenant that owns this entity.
	TenantId pulumi.StringPtrInput
}

func (StoragePolicyV2State) ElementType() reflect.Type {
	return reflect.TypeOf((*storagePolicyV2State)(nil)).Elem()
}

type storagePolicyV2Args struct {
	// - (Optional) List of external identifiers for Categories to be included in the Storage Policy. Each ID must be a valid UUID format. Maximum 20 items allowed.
	CategoryExtIds []string `pulumi:"categoryExtIds"`
	// - (Optional) Defines compression parameters for entities governed by the Storage Policy.
	CompressionSpecs []StoragePolicyV2CompressionSpec `pulumi:"compressionSpecs"`
	// - (Optional) Defines encryption parameters for entities governed by the Storage Policy.
	EncryptionSpecs []StoragePolicyV2EncryptionSpec `pulumi:"encryptionSpecs"`
	// - (Optional) Defines Fault Tolerance parameters for the entities.
	FaultToleranceSpecs []StoragePolicyV2FaultToleranceSpec `pulumi:"faultToleranceSpecs"`
	// - (Required) Storage Policy name. Must be unique and cannot exceed 64 characters.
	Name *string `pulumi:"name"`
	// - (Optional) Defines Storage Quality of Service (QOS) parameters for the entities.
	QosSpecs []StoragePolicyV2QosSpec `pulumi:"qosSpecs"`
}

// The set of arguments for constructing a StoragePolicyV2 resource.
type StoragePolicyV2Args struct {
	// - (Optional) List of external identifiers for Categories to be included in the Storage Policy. Each ID must be a valid UUID format. Maximum 20 items allowed.
	CategoryExtIds pulumi.StringArrayInput
	// - (Optional) Defines compression parameters for entities governed by the Storage Policy.
	CompressionSpecs StoragePolicyV2CompressionSpecArrayInput
	// - (Optional) Defines encryption parameters for entities governed by the Storage Policy.
	EncryptionSpecs StoragePolicyV2EncryptionSpecArrayInput
	// - (Optional) Defines Fault Tolerance parameters for the entities.
	FaultToleranceSpecs StoragePolicyV2FaultToleranceSpecArrayInput
	// - (Required) Storage Policy name. Must be unique and cannot exceed 64 characters.
	Name pulumi.StringPtrInput
	// - (Optional) Defines Storage Quality of Service (QOS) parameters for the entities.
	QosSpecs StoragePolicyV2QosSpecArrayInput
}

func (StoragePolicyV2Args) ElementType() reflect.Type {
	return reflect.TypeOf((*storagePolicyV2Args)(nil)).Elem()
}

type StoragePolicyV2Input interface {
	pulumi.Input

	ToStoragePolicyV2Output() StoragePolicyV2Output
	ToStoragePolicyV2OutputWithContext(ctx context.Context) StoragePolicyV2Output
}

func (*StoragePolicyV2) ElementType() reflect.Type {
	return reflect.TypeOf((**StoragePolicyV2)(nil)).Elem()
}

func (i *StoragePolicyV2) ToStoragePolicyV2Output() StoragePolicyV2Output {
	return i.ToStoragePolicyV2OutputWithContext(context.Background())
}

func (i *StoragePolicyV2) ToStoragePolicyV2OutputWithContext(ctx context.Context) StoragePolicyV2Output {
	return pulumi.ToOutputWithContext(ctx, i).(StoragePolicyV2Output)
}

// StoragePolicyV2ArrayInput is an input type that accepts StoragePolicyV2Array and StoragePolicyV2ArrayOutput values.
// You can construct a concrete instance of `StoragePolicyV2ArrayInput` via:
//
//	StoragePolicyV2Array{ StoragePolicyV2Args{...} }
type StoragePolicyV2ArrayInput interface {
	pulumi.Input

	ToStoragePolicyV2ArrayOutput() StoragePolicyV2ArrayOutput
	ToStoragePolicyV2ArrayOutputWithContext(context.Context) StoragePolicyV2ArrayOutput
}

type StoragePolicyV2Array []StoragePolicyV2Input

func (StoragePolicyV2Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*StoragePolicyV2)(nil)).Elem()
}

func (i StoragePolicyV2Array) ToStoragePolicyV2ArrayOutput() StoragePolicyV2ArrayOutput {
	return i.ToStoragePolicyV2ArrayOutputWithContext(context.Background())
}

func (i StoragePolicyV2Array) ToStoragePolicyV2ArrayOutputWithContext(ctx context.Context) StoragePolicyV2ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StoragePolicyV2ArrayOutput)
}

// StoragePolicyV2MapInput is an input type that accepts StoragePolicyV2Map and StoragePolicyV2MapOutput values.
// You can construct a concrete instance of `StoragePolicyV2MapInput` via:
//
//	StoragePolicyV2Map{ "key": StoragePolicyV2Args{...} }
type StoragePolicyV2MapInput interface {
	pulumi.Input

	ToStoragePolicyV2MapOutput() StoragePolicyV2MapOutput
	ToStoragePolicyV2MapOutputWithContext(context.Context) StoragePolicyV2MapOutput
}

type StoragePolicyV2Map map[string]StoragePolicyV2Input

func (StoragePolicyV2Map) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*StoragePolicyV2)(nil)).Elem()
}

func (i StoragePolicyV2Map) ToStoragePolicyV2MapOutput() StoragePolicyV2MapOutput {
	return i.ToStoragePolicyV2MapOutputWithContext(context.Background())
}

func (i StoragePolicyV2Map) ToStoragePolicyV2MapOutputWithContext(ctx context.Context) StoragePolicyV2MapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StoragePolicyV2MapOutput)
}

type StoragePolicyV2Output struct{ *pulumi.OutputState }

func (StoragePolicyV2Output) ElementType() reflect.Type {
	return reflect.TypeOf((**StoragePolicyV2)(nil)).Elem()
}

func (o StoragePolicyV2Output) ToStoragePolicyV2Output() StoragePolicyV2Output {
	return o
}

func (o StoragePolicyV2Output) ToStoragePolicyV2OutputWithContext(ctx context.Context) StoragePolicyV2Output {
	return o
}

// - (Optional) List of external identifiers for Categories to be included in the Storage Policy. Each ID must be a valid UUID format. Maximum 20 items allowed.
func (o StoragePolicyV2Output) CategoryExtIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *StoragePolicyV2) pulumi.StringArrayOutput { return v.CategoryExtIds }).(pulumi.StringArrayOutput)
}

// - (Optional) Defines compression parameters for entities governed by the Storage Policy.
func (o StoragePolicyV2Output) CompressionSpecs() StoragePolicyV2CompressionSpecArrayOutput {
	return o.ApplyT(func(v *StoragePolicyV2) StoragePolicyV2CompressionSpecArrayOutput { return v.CompressionSpecs }).(StoragePolicyV2CompressionSpecArrayOutput)
}

// - (Optional) Defines encryption parameters for entities governed by the Storage Policy.
func (o StoragePolicyV2Output) EncryptionSpecs() StoragePolicyV2EncryptionSpecArrayOutput {
	return o.ApplyT(func(v *StoragePolicyV2) StoragePolicyV2EncryptionSpecArrayOutput { return v.EncryptionSpecs }).(StoragePolicyV2EncryptionSpecArrayOutput)
}

// - (Computed) External identifier of the Storage Policy.
func (o StoragePolicyV2Output) ExtId() pulumi.StringOutput {
	return o.ApplyT(func(v *StoragePolicyV2) pulumi.StringOutput { return v.ExtId }).(pulumi.StringOutput)
}

// - (Optional) Defines Fault Tolerance parameters for the entities.
func (o StoragePolicyV2Output) FaultToleranceSpecs() StoragePolicyV2FaultToleranceSpecArrayOutput {
	return o.ApplyT(func(v *StoragePolicyV2) StoragePolicyV2FaultToleranceSpecArrayOutput { return v.FaultToleranceSpecs }).(StoragePolicyV2FaultToleranceSpecArrayOutput)
}

// - A HATEOAS style link for the response. Each link contains a user-friendly name identifying the link and an address for retrieving the particular resource.
func (o StoragePolicyV2Output) Links() StoragePolicyV2LinkArrayOutput {
	return o.ApplyT(func(v *StoragePolicyV2) StoragePolicyV2LinkArrayOutput { return v.Links }).(StoragePolicyV2LinkArrayOutput)
}

// - (Required) Storage Policy name. Must be unique and cannot exceed 64 characters.
func (o StoragePolicyV2Output) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *StoragePolicyV2) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// - (Computed) Indicates whether the policy is user-created or system-created. Valid values: `"USER"`, `"SYSTEM"`.
func (o StoragePolicyV2Output) PolicyType() pulumi.StringOutput {
	return o.ApplyT(func(v *StoragePolicyV2) pulumi.StringOutput { return v.PolicyType }).(pulumi.StringOutput)
}

// - (Optional) Defines Storage Quality of Service (QOS) parameters for the entities.
func (o StoragePolicyV2Output) QosSpecs() StoragePolicyV2QosSpecArrayOutput {
	return o.ApplyT(func(v *StoragePolicyV2) StoragePolicyV2QosSpecArrayOutput { return v.QosSpecs }).(StoragePolicyV2QosSpecArrayOutput)
}

// - A globally unique identifier that represents the tenant that owns this entity.
func (o StoragePolicyV2Output) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v *StoragePolicyV2) pulumi.StringOutput { return v.TenantId }).(pulumi.StringOutput)
}

type StoragePolicyV2ArrayOutput struct{ *pulumi.OutputState }

func (StoragePolicyV2ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*StoragePolicyV2)(nil)).Elem()
}

func (o StoragePolicyV2ArrayOutput) ToStoragePolicyV2ArrayOutput() StoragePolicyV2ArrayOutput {
	return o
}

func (o StoragePolicyV2ArrayOutput) ToStoragePolicyV2ArrayOutputWithContext(ctx context.Context) StoragePolicyV2ArrayOutput {
	return o
}

func (o StoragePolicyV2ArrayOutput) Index(i pulumi.IntInput) StoragePolicyV2Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *StoragePolicyV2 {
		return vs[0].([]*StoragePolicyV2)[vs[1].(int)]
	}).(StoragePolicyV2Output)
}

type StoragePolicyV2MapOutput struct{ *pulumi.OutputState }

func (StoragePolicyV2MapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*StoragePolicyV2)(nil)).Elem()
}

func (o StoragePolicyV2MapOutput) ToStoragePolicyV2MapOutput() StoragePolicyV2MapOutput {
	return o
}

func (o StoragePolicyV2MapOutput) ToStoragePolicyV2MapOutputWithContext(ctx context.Context) StoragePolicyV2MapOutput {
	return o
}

func (o StoragePolicyV2MapOutput) MapIndex(k pulumi.StringInput) StoragePolicyV2Output {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *StoragePolicyV2 {
		return vs[0].(map[string]*StoragePolicyV2)[vs[1].(string)]
	}).(StoragePolicyV2Output)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*StoragePolicyV2Input)(nil)).Elem(), &StoragePolicyV2{})
	pulumi.RegisterInputType(reflect.TypeOf((*StoragePolicyV2ArrayInput)(nil)).Elem(), StoragePolicyV2Array{})
	pulumi.RegisterInputType(reflect.TypeOf((*StoragePolicyV2MapInput)(nil)).Elem(), StoragePolicyV2Map{})
	pulumi.RegisterOutputType(StoragePolicyV2Output{})
	pulumi.RegisterOutputType(StoragePolicyV2ArrayOutput{})
	pulumi.RegisterOutputType(StoragePolicyV2MapOutput{})
}
