// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class ClusterAddNodeV2NodeParamBundleInfoArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// -(Optional) Name of the hypervisor bundle.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public ClusterAddNodeV2NodeParamBundleInfoArgs()
        {
        }
        public static new ClusterAddNodeV2NodeParamBundleInfoArgs Empty => new ClusterAddNodeV2NodeParamBundleInfoArgs();
    }
}
