// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class ClusterV2NetworkSmtpServerServerArgs : global::Pulumi.ResourceArgs
    {
        [Input("ipAddresses")]
        private InputList<Inputs.ClusterV2NetworkSmtpServerServerIpAddressArgs>? _ipAddresses;

        /// <summary>
        /// An unique address that identifies a device on the internet or a local network in IPv4 or IPv6 format.
        /// </summary>
        public InputList<Inputs.ClusterV2NetworkSmtpServerServerIpAddressArgs> IpAddresses
        {
            get => _ipAddresses ?? (_ipAddresses = new InputList<Inputs.ClusterV2NetworkSmtpServerServerIpAddressArgs>());
            set => _ipAddresses = value;
        }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// SMTP server password.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// SMTP port.
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// SMTP server user name.
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        public ClusterV2NetworkSmtpServerServerArgs()
        {
        }
        public static new ClusterV2NetworkSmtpServerServerArgs Empty => new ClusterV2NetworkSmtpServerServerArgs();
    }
}
