// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class GetFoundationCentralListApiKeysMetadataArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The number of records retrieved.
        /// </summary>
        [Input("length", required: true)]
        public int Length { get; set; }

        /// <summary>
        /// Offset from the start of the object list.
        /// </summary>
        [Input("offset", required: true)]
        public int Offset { get; set; }

        /// <summary>
        /// Total matches found.
        /// </summary>
        [Input("totalMatches", required: true)]
        public int TotalMatches { get; set; }

        public GetFoundationCentralListApiKeysMetadataArgs()
        {
        }
        public static new GetFoundationCentralListApiKeysMetadataArgs Empty => new GetFoundationCentralListApiKeysMetadataArgs();
    }
}
