// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class GetFoundationCentralClusterDetailsClusterStatusClusterProgressDetailInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cluster name.
        /// </summary>
        [Input("clusterName", required: true)]
        public Input<string> ClusterName { get; set; } = null!;

        [Input("messageLists", required: true)]
        private InputList<string>? _messageLists;

        /// <summary>
        /// List of messages for the client based on process state.
        /// </summary>
        public InputList<string> MessageLists
        {
            get => _messageLists ?? (_messageLists = new InputList<string>());
            set => _messageLists = value;
        }

        /// <summary>
        /// Percent completion of cluster creation process.
        /// </summary>
        [Input("percentComplete", required: true)]
        public Input<double> PercentComplete { get; set; } = null!;

        /// <summary>
        /// Current status of cluster creation process.
        /// </summary>
        [Input("status", required: true)]
        public Input<string> Status { get; set; } = null!;

        public GetFoundationCentralClusterDetailsClusterStatusClusterProgressDetailInputArgs()
        {
        }
        public static new GetFoundationCentralClusterDetailsClusterStatusClusterProgressDetailInputArgs Empty => new GetFoundationCentralClusterDetailsClusterStatusClusterProgressDetailInputArgs();
    }
}
