// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class KarbonClusterExternalLbConfigMasterNodesConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("ipv4Address", required: true)]
        public Input<string> Ipv4Address { get; set; } = null!;

        [Input("nodePoolName")]
        public Input<string>? NodePoolName { get; set; }

        public KarbonClusterExternalLbConfigMasterNodesConfigArgs()
        {
        }
        public static new KarbonClusterExternalLbConfigMasterNodesConfigArgs Empty => new KarbonClusterExternalLbConfigMasterNodesConfigArgs();
    }
}
