// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class NdbClusterPropertyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// description of cluster
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// name of the cluster to be registered
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("refId")]
        public Input<string>? RefId { get; set; }

        [Input("secure")]
        public Input<bool>? Secure { get; set; }

        [Input("value")]
        public Input<string>? Value { get; set; }

        public NdbClusterPropertyGetArgs()
        {
        }
        public static new NdbClusterPropertyGetArgs Empty => new NdbClusterPropertyGetArgs();
    }
}
