// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class NdbCloneLinkedDatabaseArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// database name
        /// </summary>
        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        [Input("databaseStatus")]
        public Input<string>? DatabaseStatus { get; set; }

        /// <summary>
        /// date created for clone
        /// </summary>
        [Input("dateCreated")]
        public Input<string>? DateCreated { get; set; }

        /// <summary>
        /// last modified date for clone
        /// </summary>
        [Input("dateModified")]
        public Input<string>? DateModified { get; set; }

        /// <summary>
        /// database instance description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("infos")]
        private InputList<Inputs.NdbCloneLinkedDatabaseInfoArgs>? _infos;

        /// <summary>
        /// info of clone
        /// </summary>
        public InputList<Inputs.NdbCloneLinkedDatabaseInfoArgs> Infos
        {
            get => _infos ?? (_infos = new InputList<Inputs.NdbCloneLinkedDatabaseInfoArgs>());
            set => _infos = value;
        }

        [Input("metric")]
        private InputMap<string>? _metric;

        /// <summary>
        /// Stores storage info regarding size, allocatedSize, usedSize and unit of calculation that seems to have been fetched from PRISM.
        /// </summary>
        public InputMap<string> Metric
        {
            get => _metric ?? (_metric = new InputMap<string>());
            set => _metric = value;
        }

        /// <summary>
        /// database instance name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("parentDatabaseId")]
        public Input<string>? ParentDatabaseId { get; set; }

        [Input("parentLinkedDatabaseId")]
        public Input<string>? ParentLinkedDatabaseId { get; set; }

        /// <summary>
        /// snapshot id from where clone is created
        /// </summary>
        [Input("snapshotId")]
        public Input<string>? SnapshotId { get; set; }

        /// <summary>
        /// status of clone
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("timezone")]
        public Input<string>? Timezone { get; set; }

        public NdbCloneLinkedDatabaseArgs()
        {
        }
        public static new NdbCloneLinkedDatabaseArgs Empty => new NdbCloneLinkedDatabaseArgs();
    }
}
