// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class NdbClusterEntityCountEngineCountMariadbDatabaseArgs : global::Pulumi.ResourceArgs
    {
        [Input("profiles")]
        private InputList<Inputs.NdbClusterEntityCountEngineCountMariadbDatabaseProfileArgs>? _profiles;
        public InputList<Inputs.NdbClusterEntityCountEngineCountMariadbDatabaseProfileArgs> Profiles
        {
            get => _profiles ?? (_profiles = new InputList<Inputs.NdbClusterEntityCountEngineCountMariadbDatabaseProfileArgs>());
            set => _profiles = value;
        }

        [Input("timeMachines")]
        public Input<int>? TimeMachines { get; set; }

        public NdbClusterEntityCountEngineCountMariadbDatabaseArgs()
        {
        }
        public static new NdbClusterEntityCountEngineCountMariadbDatabaseArgs Empty => new NdbClusterEntityCountEngineCountMariadbDatabaseArgs();
    }
}
