// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class NdbCloneActionargumentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// - (Required) name of argument
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// - (Required) value for argument
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public NdbCloneActionargumentArgs()
        {
        }
        public static new NdbCloneActionargumentArgs Empty => new NdbCloneActionargumentArgs();
    }
}
