// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class NdbDatabaseNodePropertyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// - (Required) Name of the instance.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// - (Required) value for argument
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public NdbDatabaseNodePropertyArgs()
        {
        }
        public static new NdbDatabaseNodePropertyArgs Empty => new NdbDatabaseNodePropertyArgs();
    }
}
