// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class NdbProfileSoftwareProfileArgs : global::Pulumi.ResourceArgs
    {
        [Input("availableClusterIds")]
        private InputList<string>? _availableClusterIds;

        /// <summary>
        /// specify Nutanix clusters where this profile is available.
        /// </summary>
        public InputList<string> AvailableClusterIds
        {
            get => _availableClusterIds ?? (_availableClusterIds = new InputList<string>());
            set => _availableClusterIds = value;
        }

        [Input("postgresDatabases")]
        private InputList<Inputs.NdbProfileSoftwareProfilePostgresDatabaseArgs>? _postgresDatabases;

        /// <summary>
        /// Software profile info about postgres database.
        /// * `postgres_database.source_dbserver_id`: source dbserver id where postgress software will be installed.
        /// * `postgres_database.base_profile_version_name`: name for the software profile version.
        /// * `postgres_database.base_profile_version_description`: description for the software profile version.
        /// * `postgres_database.os_notes`: a note to provide additional information about the operating system
        /// * `postgres_database.db_software_notes`: a note to provide additional information about the database software.
        /// </summary>
        public InputList<Inputs.NdbProfileSoftwareProfilePostgresDatabaseArgs> PostgresDatabases
        {
            get => _postgresDatabases ?? (_postgresDatabases = new InputList<Inputs.NdbProfileSoftwareProfilePostgresDatabaseArgs>());
            set => _postgresDatabases = value;
        }

        /// <summary>
        /// Topology of software profile. Allowed values are "cluster" and "single"
        /// </summary>
        [Input("topology", required: true)]
        public Input<string> Topology { get; set; } = null!;

        public NdbProfileSoftwareProfileArgs()
        {
        }
        public static new NdbProfileSoftwareProfileArgs Empty => new NdbProfileSoftwareProfileArgs();
    }
}
