// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class NdbRegisterDatabaseInfoBpgConfigStorageArgs : global::Pulumi.ResourceArgs
    {
        [Input("archiveStorages")]
        private InputList<Inputs.NdbRegisterDatabaseInfoBpgConfigStorageArchiveStorageArgs>? _archiveStorages;
        public InputList<Inputs.NdbRegisterDatabaseInfoBpgConfigStorageArchiveStorageArgs> ArchiveStorages
        {
            get => _archiveStorages ?? (_archiveStorages = new InputList<Inputs.NdbRegisterDatabaseInfoBpgConfigStorageArchiveStorageArgs>());
            set => _archiveStorages = value;
        }

        [Input("dataDisks")]
        private InputList<Inputs.NdbRegisterDatabaseInfoBpgConfigStorageDataDiskArgs>? _dataDisks;
        public InputList<Inputs.NdbRegisterDatabaseInfoBpgConfigStorageDataDiskArgs> DataDisks
        {
            get => _dataDisks ?? (_dataDisks = new InputList<Inputs.NdbRegisterDatabaseInfoBpgConfigStorageDataDiskArgs>());
            set => _dataDisks = value;
        }

        [Input("logDisks")]
        private InputList<Inputs.NdbRegisterDatabaseInfoBpgConfigStorageLogDiskArgs>? _logDisks;
        public InputList<Inputs.NdbRegisterDatabaseInfoBpgConfigStorageLogDiskArgs> LogDisks
        {
            get => _logDisks ?? (_logDisks = new InputList<Inputs.NdbRegisterDatabaseInfoBpgConfigStorageLogDiskArgs>());
            set => _logDisks = value;
        }

        public NdbRegisterDatabaseInfoBpgConfigStorageArgs()
        {
        }
        public static new NdbRegisterDatabaseInfoBpgConfigStorageArgs Empty => new NdbRegisterDatabaseInfoBpgConfigStorageArgs();
    }
}
