// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class NetworkSecurityPolicyV2RuleSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("applicationRuleSpecs")]
        private InputList<Inputs.NetworkSecurityPolicyV2RuleSpecApplicationRuleSpecArgs>? _applicationRuleSpecs;

        /// <summary>
        /// Application Rule Spec.
        /// </summary>
        public InputList<Inputs.NetworkSecurityPolicyV2RuleSpecApplicationRuleSpecArgs> ApplicationRuleSpecs
        {
            get => _applicationRuleSpecs ?? (_applicationRuleSpecs = new InputList<Inputs.NetworkSecurityPolicyV2RuleSpecApplicationRuleSpecArgs>());
            set => _applicationRuleSpecs = value;
        }

        [Input("intraEntityGroupRuleSpecs")]
        private InputList<Inputs.NetworkSecurityPolicyV2RuleSpecIntraEntityGroupRuleSpecArgs>? _intraEntityGroupRuleSpecs;

        /// <summary>
        /// Intra entity group Rule Spec
        /// </summary>
        public InputList<Inputs.NetworkSecurityPolicyV2RuleSpecIntraEntityGroupRuleSpecArgs> IntraEntityGroupRuleSpecs
        {
            get => _intraEntityGroupRuleSpecs ?? (_intraEntityGroupRuleSpecs = new InputList<Inputs.NetworkSecurityPolicyV2RuleSpecIntraEntityGroupRuleSpecArgs>());
            set => _intraEntityGroupRuleSpecs = value;
        }

        [Input("multiEnvIsolationRuleSpecs")]
        private InputList<Inputs.NetworkSecurityPolicyV2RuleSpecMultiEnvIsolationRuleSpecArgs>? _multiEnvIsolationRuleSpecs;

        /// <summary>
        /// Multi Environment Isolation Rule Spec.
        /// </summary>
        public InputList<Inputs.NetworkSecurityPolicyV2RuleSpecMultiEnvIsolationRuleSpecArgs> MultiEnvIsolationRuleSpecs
        {
            get => _multiEnvIsolationRuleSpecs ?? (_multiEnvIsolationRuleSpecs = new InputList<Inputs.NetworkSecurityPolicyV2RuleSpecMultiEnvIsolationRuleSpecArgs>());
            set => _multiEnvIsolationRuleSpecs = value;
        }

        [Input("twoEnvIsolationRuleSpecs")]
        private InputList<Inputs.NetworkSecurityPolicyV2RuleSpecTwoEnvIsolationRuleSpecArgs>? _twoEnvIsolationRuleSpecs;

        /// <summary>
        /// Two Environment Isolation Rule Spec.
        /// </summary>
        public InputList<Inputs.NetworkSecurityPolicyV2RuleSpecTwoEnvIsolationRuleSpecArgs> TwoEnvIsolationRuleSpecs
        {
            get => _twoEnvIsolationRuleSpecs ?? (_twoEnvIsolationRuleSpecs = new InputList<Inputs.NetworkSecurityPolicyV2RuleSpecTwoEnvIsolationRuleSpecArgs>());
            set => _twoEnvIsolationRuleSpecs = value;
        }

        public NetworkSecurityPolicyV2RuleSpecArgs()
        {
        }
        public static new NetworkSecurityPolicyV2RuleSpecArgs Empty => new NetworkSecurityPolicyV2RuleSpecArgs();
    }
}
