// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class ObjectStoreV2StorageNetworkVipIpv4Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// - The prefix length of the network to which this host IPv4 address belongs. Default for IPv4 is 32 and for IPv6 is 128.
        /// </summary>
        [Input("prefixLength")]
        public Input<int>? PrefixLength { get; set; }

        /// <summary>
        /// - The IPv4/IPv6 address of the host.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public ObjectStoreV2StorageNetworkVipIpv4Args()
        {
        }
        public static new ObjectStoreV2StorageNetworkVipIpv4Args Empty => new ObjectStoreV2StorageNetworkVipIpv4Args();
    }
}
