// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class ObjectStoreCertificateV2MetadataGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("categoryIds")]
        private InputList<string>? _categoryIds;
        public InputList<string> CategoryIds
        {
            get => _categoryIds ?? (_categoryIds = new InputList<string>());
            set => _categoryIds = value;
        }

        [Input("ownerReferenceId")]
        public Input<string>? OwnerReferenceId { get; set; }

        [Input("ownerUserName")]
        public Input<string>? OwnerUserName { get; set; }

        [Input("projectName")]
        public Input<string>? ProjectName { get; set; }

        [Input("projectReferenceId")]
        public Input<string>? ProjectReferenceId { get; set; }

        public ObjectStoreCertificateV2MetadataGetArgs()
        {
        }
        public static new ObjectStoreCertificateV2MetadataGetArgs Empty => new ObjectStoreCertificateV2MetadataGetArgs();
    }
}
