// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class PbrV2PolicyPolicyMatchProtocolParameterProtocolNumberObjectGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("protocolNumber", required: true)]
        public Input<int> ProtocolNumber { get; set; } = null!;

        public PbrV2PolicyPolicyMatchProtocolParameterProtocolNumberObjectGetArgs()
        {
        }
        public static new PbrV2PolicyPolicyMatchProtocolParameterProtocolNumberObjectGetArgs Empty => new PbrV2PolicyPolicyMatchProtocolParameterProtocolNumberObjectGetArgs();
    }
}
