// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class PcDeployV2NetworkExternalNetworkIpRangeBeginGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("ipv4s")]
        private InputList<Inputs.PcDeployV2NetworkExternalNetworkIpRangeBeginIpv4GetArgs>? _ipv4s;

        /// <summary>
        /// -(Optional) An unique address that identifies a device on the internet or a local network in IPv4 format.
        /// </summary>
        public InputList<Inputs.PcDeployV2NetworkExternalNetworkIpRangeBeginIpv4GetArgs> Ipv4s
        {
            get => _ipv4s ?? (_ipv4s = new InputList<Inputs.PcDeployV2NetworkExternalNetworkIpRangeBeginIpv4GetArgs>());
            set => _ipv4s = value;
        }

        [Input("ipv6s")]
        private InputList<Inputs.PcDeployV2NetworkExternalNetworkIpRangeBeginIpv6GetArgs>? _ipv6s;

        /// <summary>
        /// -(Optional) An unique address that identifies a device on the internet or a local network in IPv6 format.
        /// </summary>
        public InputList<Inputs.PcDeployV2NetworkExternalNetworkIpRangeBeginIpv6GetArgs> Ipv6s
        {
            get => _ipv6s ?? (_ipv6s = new InputList<Inputs.PcDeployV2NetworkExternalNetworkIpRangeBeginIpv6GetArgs>());
            set => _ipv6s = value;
        }

        public PcDeployV2NetworkExternalNetworkIpRangeBeginGetArgs()
        {
        }
        public static new PcDeployV2NetworkExternalNetworkIpRangeBeginGetArgs Empty => new PcDeployV2NetworkExternalNetworkIpRangeBeginGetArgs();
    }
}
