// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class PcRestoreSourceV2LocationObjectStoreLocationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("backupPolicies")]
        private InputList<Inputs.PcRestoreSourceV2LocationObjectStoreLocationBackupPolicyGetArgs>? _backupPolicies;

        /// <summary>
        /// -(Optional) Backup policy for the object store provided.
        /// </summary>
        public InputList<Inputs.PcRestoreSourceV2LocationObjectStoreLocationBackupPolicyGetArgs> BackupPolicies
        {
            get => _backupPolicies ?? (_backupPolicies = new InputList<Inputs.PcRestoreSourceV2LocationObjectStoreLocationBackupPolicyGetArgs>());
            set => _backupPolicies = value;
        }

        [Input("providerConfigs", required: true)]
        private InputList<Inputs.PcRestoreSourceV2LocationObjectStoreLocationProviderConfigGetArgs>? _providerConfigs;

        /// <summary>
        /// -(Required) The base model of S3 object store endpoint where domain manager is backed up.
        /// </summary>
        public InputList<Inputs.PcRestoreSourceV2LocationObjectStoreLocationProviderConfigGetArgs> ProviderConfigs
        {
            get => _providerConfigs ?? (_providerConfigs = new InputList<Inputs.PcRestoreSourceV2LocationObjectStoreLocationProviderConfigGetArgs>());
            set => _providerConfigs = value;
        }

        public PcRestoreSourceV2LocationObjectStoreLocationGetArgs()
        {
        }
        public static new PcRestoreSourceV2LocationObjectStoreLocationGetArgs Empty => new PcRestoreSourceV2LocationObjectStoreLocationGetArgs();
    }
}
