// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class ProtectionPolicyV2ReplicationConfigurationScheduleRetentionAutoRollupRetentionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// -(Required) Specifies the auto rollup retention details.
        /// </summary>
        [Input("local", required: true)]
        public Input<Inputs.ProtectionPolicyV2ReplicationConfigurationScheduleRetentionAutoRollupRetentionLocalGetArgs> Local { get; set; } = null!;

        /// <summary>
        /// -(Optional) Specifies the auto rollup retention details.
        /// </summary>
        [Input("remote")]
        public Input<Inputs.ProtectionPolicyV2ReplicationConfigurationScheduleRetentionAutoRollupRetentionRemoteGetArgs>? Remote { get; set; }

        public ProtectionPolicyV2ReplicationConfigurationScheduleRetentionAutoRollupRetentionGetArgs()
        {
        }
        public static new ProtectionPolicyV2ReplicationConfigurationScheduleRetentionAutoRollupRetentionGetArgs Empty => new ProtectionPolicyV2ReplicationConfigurationScheduleRetentionAutoRollupRetentionGetArgs();
    }
}
