// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class SubnetV2VpcExternalSubnetActiveGatewayNodeArgs : global::Pulumi.ResourceArgs
    {
        [Input("nodeId")]
        public Input<string>? NodeId { get; set; }

        [Input("nodeIpAddresses")]
        private InputList<Inputs.SubnetV2VpcExternalSubnetActiveGatewayNodeNodeIpAddressArgs>? _nodeIpAddresses;
        public InputList<Inputs.SubnetV2VpcExternalSubnetActiveGatewayNodeNodeIpAddressArgs> NodeIpAddresses
        {
            get => _nodeIpAddresses ?? (_nodeIpAddresses = new InputList<Inputs.SubnetV2VpcExternalSubnetActiveGatewayNodeNodeIpAddressArgs>());
            set => _nodeIpAddresses = value;
        }

        public SubnetV2VpcExternalSubnetActiveGatewayNodeArgs()
        {
        }
        public static new SubnetV2VpcExternalSubnetActiveGatewayNodeArgs Empty => new SubnetV2VpcExternalSubnetActiveGatewayNodeArgs();
    }
}
