// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class TemplateV2CreatedByAdditionalAttributeGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("values")]
        private InputList<Inputs.TemplateV2CreatedByAdditionalAttributeValueGetArgs>? _values;
        public InputList<Inputs.TemplateV2CreatedByAdditionalAttributeValueGetArgs> Values
        {
            get => _values ?? (_values = new InputList<Inputs.TemplateV2CreatedByAdditionalAttributeValueGetArgs>());
            set => _values = value;
        }

        public TemplateV2CreatedByAdditionalAttributeGetArgs()
        {
        }
        public static new TemplateV2CreatedByAdditionalAttributeGetArgs Empty => new TemplateV2CreatedByAdditionalAttributeGetArgs();
    }
}
