// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class TemplateV2TemplateVersionSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("createTime")]
        public Input<string>? CreateTime { get; set; }

        [Input("createdBies")]
        private InputList<Inputs.TemplateV2TemplateVersionSpecCreatedByArgs>? _createdBies;
        public InputList<Inputs.TemplateV2TemplateVersionSpecCreatedByArgs> CreatedBies
        {
            get => _createdBies ?? (_createdBies = new InputList<Inputs.TemplateV2TemplateVersionSpecCreatedByArgs>());
            set => _createdBies = value;
        }

        [Input("extId")]
        public Input<string>? ExtId { get; set; }

        [Input("isActiveVersion")]
        public Input<bool>? IsActiveVersion { get; set; }

        [Input("isGcOverrideEnabled")]
        public Input<bool>? IsGcOverrideEnabled { get; set; }

        [Input("links")]
        private InputList<Inputs.TemplateV2TemplateVersionSpecLinkArgs>? _links;
        public InputList<Inputs.TemplateV2TemplateVersionSpecLinkArgs> Links
        {
            get => _links ?? (_links = new InputList<Inputs.TemplateV2TemplateVersionSpecLinkArgs>());
            set => _links = value;
        }

        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        [Input("versionDescription")]
        public Input<string>? VersionDescription { get; set; }

        [Input("versionName")]
        public Input<string>? VersionName { get; set; }

        [Input("versionSource", required: true)]
        public Input<Inputs.TemplateV2TemplateVersionSpecVersionSourceArgs> VersionSource { get; set; } = null!;

        [Input("versionSourceDiscriminator")]
        public Input<string>? VersionSourceDiscriminator { get; set; }

        [Input("vmSpecs")]
        private InputList<Inputs.TemplateV2TemplateVersionSpecVmSpecArgs>? _vmSpecs;
        public InputList<Inputs.TemplateV2TemplateVersionSpecVmSpecArgs> VmSpecs
        {
            get => _vmSpecs ?? (_vmSpecs = new InputList<Inputs.TemplateV2TemplateVersionSpecVmSpecArgs>());
            set => _vmSpecs = value;
        }

        public TemplateV2TemplateVersionSpecArgs()
        {
        }
        public static new TemplateV2TemplateVersionSpecArgs Empty => new TemplateV2TemplateVersionSpecArgs();
    }
}
