// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class TemplateV2TemplateVersionSpecVmSpecGpusGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("deviceId")]
        public Input<int>? DeviceId { get; set; }

        [Input("extId")]
        public Input<string>? ExtId { get; set; }

        [Input("fraction")]
        public Input<int>? Fraction { get; set; }

        [Input("frameBufferSizeBytes")]
        public Input<int>? FrameBufferSizeBytes { get; set; }

        [Input("guestDriverVersion")]
        public Input<string>? GuestDriverVersion { get; set; }

        [Input("links")]
        private InputList<Inputs.TemplateV2TemplateVersionSpecVmSpecGpusLinkGetArgs>? _links;
        public InputList<Inputs.TemplateV2TemplateVersionSpecVmSpecGpusLinkGetArgs> Links
        {
            get => _links ?? (_links = new InputList<Inputs.TemplateV2TemplateVersionSpecVmSpecGpusLinkGetArgs>());
            set => _links = value;
        }

        [Input("mode")]
        public Input<string>? Mode { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("numVirtualDisplayHeads")]
        public Input<int>? NumVirtualDisplayHeads { get; set; }

        [Input("pciAddresses")]
        private InputList<Inputs.TemplateV2TemplateVersionSpecVmSpecGpusPciAddressGetArgs>? _pciAddresses;
        public InputList<Inputs.TemplateV2TemplateVersionSpecVmSpecGpusPciAddressGetArgs> PciAddresses
        {
            get => _pciAddresses ?? (_pciAddresses = new InputList<Inputs.TemplateV2TemplateVersionSpecVmSpecGpusPciAddressGetArgs>());
            set => _pciAddresses = value;
        }

        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        [Input("vendor")]
        public Input<string>? Vendor { get; set; }

        public TemplateV2TemplateVersionSpecVmSpecGpusGetArgs()
        {
        }
        public static new TemplateV2TemplateVersionSpecVmSpecGpusGetArgs Empty => new TemplateV2TemplateVersionSpecVmSpecGpusGetArgs();
    }
}
