// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class VirtualMachineV2BootConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("legacyBoots")]
        private InputList<Inputs.VirtualMachineV2BootConfigLegacyBootGetArgs>? _legacyBoots;

        /// <summary>
        /// LegacyBoot config Object
        /// </summary>
        public InputList<Inputs.VirtualMachineV2BootConfigLegacyBootGetArgs> LegacyBoots
        {
            get => _legacyBoots ?? (_legacyBoots = new InputList<Inputs.VirtualMachineV2BootConfigLegacyBootGetArgs>());
            set => _legacyBoots = value;
        }

        [Input("uefiBoots")]
        private InputList<Inputs.VirtualMachineV2BootConfigUefiBootGetArgs>? _uefiBoots;

        /// <summary>
        /// UefiBoot config Object
        /// </summary>
        public InputList<Inputs.VirtualMachineV2BootConfigUefiBootGetArgs> UefiBoots
        {
            get => _uefiBoots ?? (_uefiBoots = new InputList<Inputs.VirtualMachineV2BootConfigUefiBootGetArgs>());
            set => _uefiBoots = value;
        }

        public VirtualMachineV2BootConfigGetArgs()
        {
        }
        public static new VirtualMachineV2BootConfigGetArgs Empty => new VirtualMachineV2BootConfigGetArgs();
    }
}
