// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class VirtualMachineV2GuestCustomizationConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("cloudInits")]
        private InputList<Inputs.VirtualMachineV2GuestCustomizationConfigCloudInitArgs>? _cloudInits;
        public InputList<Inputs.VirtualMachineV2GuestCustomizationConfigCloudInitArgs> CloudInits
        {
            get => _cloudInits ?? (_cloudInits = new InputList<Inputs.VirtualMachineV2GuestCustomizationConfigCloudInitArgs>());
            set => _cloudInits = value;
        }

        [Input("syspreps")]
        private InputList<Inputs.VirtualMachineV2GuestCustomizationConfigSysprepArgs>? _syspreps;
        public InputList<Inputs.VirtualMachineV2GuestCustomizationConfigSysprepArgs> Syspreps
        {
            get => _syspreps ?? (_syspreps = new InputList<Inputs.VirtualMachineV2GuestCustomizationConfigSysprepArgs>());
            set => _syspreps = value;
        }

        public VirtualMachineV2GuestCustomizationConfigArgs()
        {
        }
        public static new VirtualMachineV2GuestCustomizationConfigArgs Empty => new VirtualMachineV2GuestCustomizationConfigArgs();
    }
}
