// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class VirtualMachineV2DiskBackingInfoVmDiskStorageConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Indicates whether the virtual disk is pinned to the hot tier or not.
        /// </summary>
        [Input("isFlashModeEnabled")]
        public Input<bool>? IsFlashModeEnabled { get; set; }

        public VirtualMachineV2DiskBackingInfoVmDiskStorageConfigArgs()
        {
        }
        public static new VirtualMachineV2DiskBackingInfoVmDiskStorageConfigArgs Empty => new VirtualMachineV2DiskBackingInfoVmDiskStorageConfigArgs();
    }
}
