// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("dataSources")]
        private InputList<Inputs.VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoDataSourceGetArgs>? _dataSources;
        public InputList<Inputs.VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoDataSourceGetArgs> DataSources
        {
            get => _dataSources ?? (_dataSources = new InputList<Inputs.VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoDataSourceGetArgs>());
            set => _dataSources = value;
        }

        [Input("diskExtId")]
        public Input<string>? DiskExtId { get; set; }

        [Input("diskSizeBytes")]
        public Input<int>? DiskSizeBytes { get; set; }

        [Input("isMigrationInProgress")]
        public Input<bool>? IsMigrationInProgress { get; set; }

        [Input("storageConfigs")]
        private InputList<Inputs.VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoStorageConfigGetArgs>? _storageConfigs;

        /// <summary>
        /// Storage configuration for VM.
        /// </summary>
        public InputList<Inputs.VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoStorageConfigGetArgs> StorageConfigs
        {
            get => _storageConfigs ?? (_storageConfigs = new InputList<Inputs.VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoStorageConfigGetArgs>());
            set => _storageConfigs = value;
        }

        [Input("storageContainers")]
        private InputList<Inputs.VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoStorageContainerGetArgs>? _storageContainers;
        public InputList<Inputs.VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoStorageContainerGetArgs> StorageContainers
        {
            get => _storageContainers ?? (_storageContainers = new InputList<Inputs.VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoStorageContainerGetArgs>());
            set => _storageContainers = value;
        }

        public VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoGetArgs()
        {
        }
        public static new VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoGetArgs Empty => new VirtualMachineV2BootConfigUefiBootNvramDeviceBackingStorageInfoGetArgs();
    }
}
