// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class VirtualMachineV2GuestCustomizationConfigCloudInitCloudInitScriptArgs : global::Pulumi.ResourceArgs
    {
        [Input("customKeyValues")]
        private InputList<Inputs.VirtualMachineV2GuestCustomizationConfigCloudInitCloudInitScriptCustomKeyValueArgs>? _customKeyValues;
        public InputList<Inputs.VirtualMachineV2GuestCustomizationConfigCloudInitCloudInitScriptCustomKeyValueArgs> CustomKeyValues
        {
            get => _customKeyValues ?? (_customKeyValues = new InputList<Inputs.VirtualMachineV2GuestCustomizationConfigCloudInitCloudInitScriptCustomKeyValueArgs>());
            set => _customKeyValues = value;
        }

        [Input("userDatas")]
        private InputList<Inputs.VirtualMachineV2GuestCustomizationConfigCloudInitCloudInitScriptUserDataArgs>? _userDatas;
        public InputList<Inputs.VirtualMachineV2GuestCustomizationConfigCloudInitCloudInitScriptUserDataArgs> UserDatas
        {
            get => _userDatas ?? (_userDatas = new InputList<Inputs.VirtualMachineV2GuestCustomizationConfigCloudInitCloudInitScriptUserDataArgs>());
            set => _userDatas = value;
        }

        public VirtualMachineV2GuestCustomizationConfigCloudInitCloudInitScriptArgs()
        {
        }
        public static new VirtualMachineV2GuestCustomizationConfigCloudInitCloudInitScriptArgs Empty => new VirtualMachineV2GuestCustomizationConfigCloudInitCloudInitScriptArgs();
    }
}
