// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class VmCloneV2BootConfigUefiBootNvramDeviceBackingStorageInfoStorageContainerGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("extId")]
        public Input<string>? ExtId { get; set; }

        public VmCloneV2BootConfigUefiBootNvramDeviceBackingStorageInfoStorageContainerGetArgs()
        {
        }
        public static new VmCloneV2BootConfigUefiBootNvramDeviceBackingStorageInfoStorageContainerGetArgs Empty => new VmCloneV2BootConfigUefiBootNvramDeviceBackingStorageInfoStorageContainerGetArgs();
    }
}
