// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class VmCloneV2CdRomBackingInfoStorageConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("isFlashModeEnabled")]
        public Input<bool>? IsFlashModeEnabled { get; set; }

        public VmCloneV2CdRomBackingInfoStorageConfigGetArgs()
        {
        }
        public static new VmCloneV2CdRomBackingInfoStorageConfigGetArgs Empty => new VmCloneV2CdRomBackingInfoStorageConfigGetArgs();
    }
}
