// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class VmCloneV2GuestCustomizationConfigSysprepGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// - (Optional) Whether the guest will be freshly installed using this unattend configuration, or whether this unattend configuration will be applied to a pre-prepared image. Default is `PREPARED`.
        /// Valid values are:
        /// - `PREPARED` is done when sysprep is used to finalize Windows installation from an installed Windows and file name it is searching `unattend.xml` for &lt;span pulumi-lang-nodejs="`unattendXml`" pulumi-lang-dotnet="`UnattendXml`" pulumi-lang-go="`unattendXml`" pulumi-lang-python="`unattend_xml`" pulumi-lang-yaml="`unattendXml`" pulumi-lang-java="`unattendXml`" pulumi-lang-hcl="`unattend_xml`"&gt;`unattendXml`&lt;/span&gt; parameter
        /// - `FRESH` is done when sysprep is used to install Windows from ISO and file name it is searching `autounattend.xml` for &lt;span pulumi-lang-nodejs="`unattendXml`" pulumi-lang-dotnet="`UnattendXml`" pulumi-lang-go="`unattendXml`" pulumi-lang-python="`unattend_xml`" pulumi-lang-yaml="`unattendXml`" pulumi-lang-java="`unattendXml`" pulumi-lang-hcl="`unattend_xml`"&gt;`unattendXml`&lt;/span&gt; parameter
        /// </summary>
        [Input("installType")]
        public Input<string>? InstallType { get; set; }

        [Input("sysprepScripts")]
        private InputList<Inputs.VmCloneV2GuestCustomizationConfigSysprepSysprepScriptGetArgs>? _sysprepScripts;
        public InputList<Inputs.VmCloneV2GuestCustomizationConfigSysprepSysprepScriptGetArgs> SysprepScripts
        {
            get => _sysprepScripts ?? (_sysprepScripts = new InputList<Inputs.VmCloneV2GuestCustomizationConfigSysprepSysprepScriptGetArgs>());
            set => _sysprepScripts = value;
        }

        public VmCloneV2GuestCustomizationConfigSysprepGetArgs()
        {
        }
        public static new VmCloneV2GuestCustomizationConfigSysprepGetArgs Empty => new VmCloneV2GuestCustomizationConfigSysprepGetArgs();
    }
}
