// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Nutanix.Inputs
{

    public sealed class VmCloneV2DiskBackingInfoArgs : global::Pulumi.ResourceArgs
    {
        [Input("adfsVolumeGroupReferences")]
        private InputList<Inputs.VmCloneV2DiskBackingInfoAdfsVolumeGroupReferenceArgs>? _adfsVolumeGroupReferences;
        public InputList<Inputs.VmCloneV2DiskBackingInfoAdfsVolumeGroupReferenceArgs> AdfsVolumeGroupReferences
        {
            get => _adfsVolumeGroupReferences ?? (_adfsVolumeGroupReferences = new InputList<Inputs.VmCloneV2DiskBackingInfoAdfsVolumeGroupReferenceArgs>());
            set => _adfsVolumeGroupReferences = value;
        }

        [Input("vmDisks")]
        private InputList<Inputs.VmCloneV2DiskBackingInfoVmDiskArgs>? _vmDisks;
        public InputList<Inputs.VmCloneV2DiskBackingInfoVmDiskArgs> VmDisks
        {
            get => _vmDisks ?? (_vmDisks = new InputList<Inputs.VmCloneV2DiskBackingInfoVmDiskArgs>());
            set => _vmDisks = value;
        }

        public VmCloneV2DiskBackingInfoArgs()
        {
        }
        public static new VmCloneV2DiskBackingInfoArgs Empty => new VmCloneV2DiskBackingInfoArgs();
    }
}
