// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAssertHelper(args?: GetAssertHelperArgs, opts?: pulumi.InvokeOptions): Promise<GetAssertHelperResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nutanix:index/getAssertHelper:getAssertHelper", {
        "checks": args.checks,
    }, opts);
}

/**
 * A collection of arguments for invoking getAssertHelper.
 */
export interface GetAssertHelperArgs {
    checks?: inputs.GetAssertHelperCheck[];
}

/**
 * A collection of values returned by getAssertHelper.
 */
export interface GetAssertHelperResult {
    readonly checks?: outputs.GetAssertHelperCheck[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
export function getAssertHelperOutput(args?: GetAssertHelperOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAssertHelperResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nutanix:index/getAssertHelper:getAssertHelper", {
        "checks": args.checks,
    }, opts);
}

/**
 * A collection of arguments for invoking getAssertHelper.
 */
export interface GetAssertHelperOutputArgs {
    checks?: pulumi.Input<pulumi.Input<inputs.GetAssertHelperCheckArgs>[]>;
}
