// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides a datasource to retrieve list of address groups.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as nutanix from "@pulumi/nutanix";
 *
 * const addrGroups = nutanix.getAddressGroups({});
 * ```
 */
export function getAddressGroups(args?: GetAddressGroupsArgs, opts?: pulumi.InvokeOptions): Promise<GetAddressGroupsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nutanix:index/getAddressGroups:getAddressGroups", {
        "metadatas": args.metadatas,
    }, opts);
}

/**
 * A collection of arguments for invoking getAddressGroups.
 */
export interface GetAddressGroupsArgs {
    /**
     * - (Optional) Use metadata to specify filters
     */
    metadatas?: inputs.GetAddressGroupsMetadata[];
}

/**
 * A collection of values returned by getAddressGroups.
 */
export interface GetAddressGroupsResult {
    /**
     * - (ReadOnly) List of address groups
     */
    readonly entities: outputs.GetAddressGroupsEntity[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * - (Optional) Use metadata to specify filters
     */
    readonly metadatas: outputs.GetAddressGroupsMetadata[];
}
/**
 * Provides a datasource to retrieve list of address groups.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as nutanix from "@pulumi/nutanix";
 *
 * const addrGroups = nutanix.getAddressGroups({});
 * ```
 */
export function getAddressGroupsOutput(args?: GetAddressGroupsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAddressGroupsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nutanix:index/getAddressGroups:getAddressGroups", {
        "metadatas": args.metadatas,
    }, opts);
}

/**
 * A collection of arguments for invoking getAddressGroups.
 */
export interface GetAddressGroupsOutputArgs {
    /**
     * - (Optional) Use metadata to specify filters
     */
    metadatas?: pulumi.Input<pulumi.Input<inputs.GetAddressGroupsMetadataArgs>[]>;
}
