// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSamlIdentityProviderV2(args: GetSamlIdentityProviderV2Args, opts?: pulumi.InvokeOptions): Promise<GetSamlIdentityProviderV2Result> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nutanix:index/getSamlIdentityProviderV2:getSamlIdentityProviderV2", {
        "extId": args.extId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSamlIdentityProviderV2.
 */
export interface GetSamlIdentityProviderV2Args {
    extId: string;
}

/**
 * A collection of values returned by getSamlIdentityProviderV2.
 */
export interface GetSamlIdentityProviderV2Result {
    readonly createdBy: string;
    readonly createdTime: string;
    readonly customAttributes: string[];
    readonly emailAttribute: string;
    readonly entityIssuer: string;
    readonly extId: string;
    readonly groupsAttribute: string;
    readonly groupsDelim: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly idpMetadatas: outputs.GetSamlIdentityProviderV2IdpMetadata[];
    readonly isSignedAuthnReqEnabled: boolean;
    readonly lastUpdatedTime: string;
    readonly name: string;
    readonly usernameAttribute: string;
}
export function getSamlIdentityProviderV2Output(args: GetSamlIdentityProviderV2OutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSamlIdentityProviderV2Result> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nutanix:index/getSamlIdentityProviderV2:getSamlIdentityProviderV2", {
        "extId": args.extId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSamlIdentityProviderV2.
 */
export interface GetSamlIdentityProviderV2OutputArgs {
    extId: pulumi.Input<string>;
}
