// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Downloads an OVA based on the given external identifier. This is a stream download of the OVA file..
 */
export class OvaDownloadV2 extends pulumi.CustomResource {
    /**
     * Get an existing OvaDownloadV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OvaDownloadV2State, opts?: pulumi.CustomResourceOptions): OvaDownloadV2 {
        return new OvaDownloadV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nutanix:index/ovaDownloadV2:OvaDownloadV2';

    /**
     * Returns true if the given object is an instance of OvaDownloadV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OvaDownloadV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OvaDownloadV2.__pulumiType;
    }

    /**
     * -(Required) The external identifier for an OVA.
     */
    declare public readonly ovaExtId: pulumi.Output<string>;
    declare public /*out*/ readonly ovaFilePath: pulumi.Output<string>;

    /**
     * Create a OvaDownloadV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OvaDownloadV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OvaDownloadV2Args | OvaDownloadV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OvaDownloadV2State | undefined;
            resourceInputs["ovaExtId"] = state?.ovaExtId;
            resourceInputs["ovaFilePath"] = state?.ovaFilePath;
        } else {
            const args = argsOrState as OvaDownloadV2Args | undefined;
            if (args?.ovaExtId === undefined && !opts.urn) {
                throw new Error("Missing required property 'ovaExtId'");
            }
            resourceInputs["ovaExtId"] = args?.ovaExtId;
            resourceInputs["ovaFilePath"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OvaDownloadV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering OvaDownloadV2 resources.
 */
export interface OvaDownloadV2State {
    /**
     * -(Required) The external identifier for an OVA.
     */
    ovaExtId?: pulumi.Input<string>;
    ovaFilePath?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a OvaDownloadV2 resource.
 */
export interface OvaDownloadV2Args {
    /**
     * -(Required) The external identifier for an OVA.
     */
    ovaExtId: pulumi.Input<string>;
}
