// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Unregister a registered remote cluster from the local cluster. This process is asynchronous, creating an un-registration task and returning its UUID.
 */
export class PcUnregistrationV2 extends pulumi.CustomResource {
    /**
     * Get an existing PcUnregistrationV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PcUnregistrationV2State, opts?: pulumi.CustomResourceOptions): PcUnregistrationV2 {
        return new PcUnregistrationV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nutanix:index/pcUnregistrationV2:PcUnregistrationV2';

    /**
     * Returns true if the given object is an instance of PcUnregistrationV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PcUnregistrationV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PcUnregistrationV2.__pulumiType;
    }

    /**
     * -(Required) Cluster UUID of a remote cluster.
     *
     * See detailed information in [Nutanix PC Unregistration V4](https://developers.nutanix.com/api-reference?namespace=prism&version=v4.0#tag/DomainManager/operation/unregister).
     */
    declare public readonly extId: pulumi.Output<string>;
    /**
     * -(Required) The external identifier of the domain manager (Prism Central) resource
     */
    declare public readonly pcExtId: pulumi.Output<string>;

    /**
     * Create a PcUnregistrationV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PcUnregistrationV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PcUnregistrationV2Args | PcUnregistrationV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PcUnregistrationV2State | undefined;
            resourceInputs["extId"] = state?.extId;
            resourceInputs["pcExtId"] = state?.pcExtId;
        } else {
            const args = argsOrState as PcUnregistrationV2Args | undefined;
            if (args?.extId === undefined && !opts.urn) {
                throw new Error("Missing required property 'extId'");
            }
            if (args?.pcExtId === undefined && !opts.urn) {
                throw new Error("Missing required property 'pcExtId'");
            }
            resourceInputs["extId"] = args?.extId;
            resourceInputs["pcExtId"] = args?.pcExtId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PcUnregistrationV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PcUnregistrationV2 resources.
 */
export interface PcUnregistrationV2State {
    /**
     * -(Required) Cluster UUID of a remote cluster.
     *
     * See detailed information in [Nutanix PC Unregistration V4](https://developers.nutanix.com/api-reference?namespace=prism&version=v4.0#tag/DomainManager/operation/unregister).
     */
    extId?: pulumi.Input<string>;
    /**
     * -(Required) The external identifier of the domain manager (Prism Central) resource
     */
    pcExtId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PcUnregistrationV2 resource.
 */
export interface PcUnregistrationV2Args {
    /**
     * -(Required) Cluster UUID of a remote cluster.
     *
     * See detailed information in [Nutanix PC Unregistration V4](https://developers.nutanix.com/api-reference?namespace=prism&version=v4.0#tag/DomainManager/operation/unregister).
     */
    extId: pulumi.Input<string>;
    /**
     * -(Required) The external identifier of the domain manager (Prism Central) resource
     */
    pcExtId: pulumi.Input<string>;
}
